### ISSUE TITLE
Template error on /admin/key/edit

### ISSUE THREAD

**Issue by wdoekes** [ngoduykhanh/PowerDNS-Admin#1013]
Hi!

When trying to add the first API Key, I get a 500 error:
```python
def edit_key(key_id=None):
    domains = Domain.query.all()
    roles = Role.query.all()
    apikey = None
    create = True
    plain_key = None

    if key_id:
        apikey = ApiKey.query.filter(ApiKey.id == key_id).first()
        create = False

        if not apikey:
            return render_template('errors/404.html'), 404

    if request.method == 'GET':
        return render_template('admin_edit_key.html',
                               key=apikey,
                               domains=domains,
                               roles=roles,
                               create=create)
```
So, `apikey` is `None`.

And in the template `powerdnsadmin/templates/admin_edit_key.html`, we get here:
```html
                            <select multiple="multiple" class="form-control" id="key_multi_domain"
                                name="key_multi_domain">
                                {% for domain in domains %}
                                    <option {% if domain in key.domains %}selected{% endif %} value="{{ domain.name }}">{{ domain.name }}</option>
                                {% endfor %}
                            </select>
```
There, key is None, while domain is something. So we get `domain in None.domains`:
```
[2021-10-07 12:43:47,711] [app.py:1891] ERROR - Exception on /admin/key/edit [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
...
  File "/app/powerdnsadmin/templates/admin_edit_key.html", line 2, in top-level template code
    {% set active_page = "admin_keys" %}
  File "/app/powerdnsadmin/templates/base.html", line 183, in top-level template code
    {% block content %}
  File "/app/powerdnsadmin/templates/admin_edit_key.html", line 62, in block 'content'
    <option {% if domain in key.domains %}selected{% endif %} value="{{ domain.name }}">{{ domain.name }}</option>
jinja2.exceptions.UndefinedError: 'None' has no attribute 'domains'
```
I'm running v0.2.3-29-g993e02b@sha256:18404b50c25b7f1ccf35f846a54a7c8534db896491d2af9c11027bd97c789d47, but it doesn't look like it is fixed in a later version, if I glance at the source.

(It also looks like this is not the only place where the key is expected to be non-None in this template file.)

Cheers,
Walter

**Comment by wdoekes** [comment]
Apparently this is #938, #950.

**Comment by ngoduykhanh** [comment]
Closing as #950 was merged
