### ISSUE TITLE
Setup: failed with error code 1 in ... mysqlclient

### ISSUE THREAD

**Issue by TCB13** [ngoduykhanh/PowerDNS-Admin#248]
Hello,

I was trying to install this under Debian but it fails with the following error:

```
Collecting mysqlclient==1.3.12 (from -r requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/6f/86/bad31f1c1bb0cc99e88ca2adb7cb5c71f7a6540c1bb001480513de76a931/mysqlclient-1.3.12.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 11.7MB/s 
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qdpxBF/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qdpxBF/mysqlclient/
```

Any ideia on what be causing this? Thank you.

```
python --version
Python 2.7.13

lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch

mysql --version
mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

**Comment by TCB13** [comment]
So... running `apt install libmariadbclient-dev` fixes this.

**Comment by Perflyst** [comment]
This is not working anymore with Debian 10.
`libmariadbclient-dev is already the newest version (1:10.3.17-0+deb10u1).`
`libmariadb-dev is already the newest version (1:10.3.17-0+deb10u1).`

```console
root@server ~ # python --version
Python 2.7.16
root@server ~ # python3 --version
Python 3.7.3
root@server ~ # mariadb --version
mariadb  Ver 15.1 Distrib 10.3.17-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

**Comment by Perflyst** [comment]
Well, ok https://stackoverflow.com/a/52718646

for MariaDB 10.1: `apt-get install libmariadbclient-dev`
for MariaDB 10.2: `apt-get install libmariadb-dev`
for MariaDB 10.3: `apt-get install libmariadb-dev-compat`
