### ISSUE TITLE
404 Client Error: Not Found

### ISSUE THREAD

**Issue by ClocxHD** [ngoduykhanh/PowerDNS-Admin#254]
Hello,

i have problems with getting PowerDNS-Admin to work.
If i open the webinterface, there are no statistics.
the log-file shows the following:
```
[ERROR] Can not get server statistics.
[DEBUG] Traceback (most recent call last):
  File "/var/sites/htdocs/xxxxxxxxxx/PowerDNS-Admin/app/lib/utils.py", line 95, in fetch_remote
    r.raise_for_status()
  File "/var/sites/htdocs/xxxxxxxxxx/PowerDNS-Admin/flask/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:8081/servers/localhost/statistics

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/sites/htdocs/xxxxxxxxxx/PowerDNS-Admin/app/models.py", line 1381, in get_statistic
    jdata = utils.fetch_json(urljoin(PDNS_STATS_URL, API_EXTENDED_URL + '/servers/{0}/statistics'.format(self.server_id)), headers=headers, method='GET')
  File "/var/sites/htdocs/xxxxxxxxxx/PowerDNS-Admin/app/lib/utils.py", line 104, in fetch_json
    accept='application/json; q=1')
  File "/var/sites/htdocs/xxxxxxxxxx/PowerDNS-Admin/app/lib/utils.py", line 97, in fetch_remote
    raise RuntimeError('Error while fetching {0}'.format(remote_url)) from e
RuntimeError: Error while fetching http://127.0.0.1:8081/servers/localhost/statistics
```

Any ideas?

I also get this message if i try to add a domain.

**Comment by ngoduykhanh** [comment]
It means that your PowerDNS server API is not available. Have you configured it yet?

**Comment by ClocxHD** [comment]
Yes, but the problem was, that i updatet the PowerDNS Server, but forgot to change the version number in the PowerDNS-Admin Config!
