### ISSUE TITLE
ModuleNotFoundError: No module named 'ldap.filter'

### ISSUE THREAD

**Issue by chinarhcx** [ngoduykhanh/PowerDNS-Admin#257]
CentOS 7 install powerdns-Admin:
(PowerDNS-Admin) [root@pwdns-01 PowerDNS-Admin-master]# ./create_db.py 
Traceback (most recent call last):
  File "./create_db.py", line 11, in <module>
    from app import d
  File "/opt/PowerDNS-Admin-master/app/__init__.py", line 95, in <module>
    from app import views, models
  File "/opt/PowerDNS-Admin-master/app/views.py", line 20, in <module>
    from .models import User, Domain, Record, Server, History, Anonymous, Setting, DomainSetting, DomainTemplate, DomainTemplateRecord
  File "/opt/PowerDNS-Admin-master/app/models.py", line 3, in <module>
    import ldap.filter
ModuleNotFoundError: No module named 'ldap.filter'

env question,ok.sorry

**Comment by ngoduykhanh** [comment]
Have installed package from `requirements.txt` file ?
