### ISSUE TITLE
Apache WSGI Error

### ISSUE THREAD

**Issue by mchlrv** [ngoduykhanh/PowerDNS-Admin#265]
I'm trying to setup PowerDNS-Admin with Apache WSGI but get same error as #160 
However after I followed all the recommended configuration settings, including setting up a separate user and group I still get the same error. 

```
[Fri May 25 13:19:28.039503 2018] [:error] [pid 28912] [remote 127.0.0.1:152] mod_wsgi (pid=28912): Target WSGI script '/opt/powerdnsadmin/powerdnsadmin.wsgi' cannot be loaded as Python module.
[Fri May 25 13:19:28.039548 2018] [:error] [pid 28912] [remote 127.0.0.1:152] mod_wsgi (pid=28912): Exception occurred processing WSGI script '/opt/powerdnsadmin/powerdnsadmin.wsgi'.
[Fri May 25 13:19:28.039587 2018] [:error] [pid 28912] [remote 127.0.0.1:152] Traceback (most recent call last):
[Fri May 25 13:19:28.039624 2018] [:error] [pid 28912] [remote 127.0.0.1:152]   File "/opt/powerdnsadmin/powerdnsadmin.wsgi", line 7, in <module>
[Fri May 25 13:19:28.039676 2018] [:error] [pid 28912] [remote 127.0.0.1:152]     from app import app as application
[Fri May 25 13:19:28.039703 2018] [:error] [pid 28912] [remote 127.0.0.1:152]   File "/opt/powerdnsadmin/app/__init__.py", line 1, in <module>
[Fri May 25 13:19:28.039745 2018] [:error] [pid 28912] [remote 127.0.0.1:152]     from werkzeug.contrib.fixers import ProxyFix
[Fri May 25 13:19:28.039782 2018] [:error] [pid 28912] [remote 127.0.0.1:152] ImportError: No module named werkzeug.contrib.fixers
```

Does anybody know how to debug this?

**Comment by mchlrv** [comment]
It turned out that I was using the wrong (Centos 7 default) wsgi_mod version. After removing this wsgi_mod version I installed the correct one with PIP:

```
yum install httpd-devel
pip3 install mod-wsgi
mod_wsgi-express install-module > /etc/httpd/conf.modules.d/02-wsgi.conf
```
Restarted Apache and everything started working.
