### ISSUE TITLE
db init not working

### ISSUE THREAD

**Issue by shnacharya** [ngoduykhanh/PowerDNS-Admin#292]
# flask db init
Traceback (most recent call last):
  File "/opt/web/PowerDNS-Admin/flask/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/opt/web/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/opt/web/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/opt/web/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/web/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/web/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/web/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/web/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/flask/cli.py", line 256, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/opt/web/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/opt/web/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/flask/cli.py", line 90, in locate_app
    __import__(module)
  File "/opt/web/PowerDNS-Admin/app/__init__.py", line 109, in <module>
    from app import views, models
  File "/opt/web/PowerDNS-Admin/app/views.py", line 20, in <module>
    from .models import User, Account, Domain, Record, Server, History, Anonymous, Setting, DomainSetting, DomainTemplate, DomainTemplateRecord
  File "/opt/web/PowerDNS-Admin/app/models.py", line 16, in <module>
    from urllib.parse import urljoin
ImportError: No module named parse

**Comment by electron79** [comment]
Hello, i have the equal problem on Debian Stretch:

# flask db upgrade
Traceback (most recent call last):
  File "/opt/PowerDNS-Admin/flask/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/opt/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/opt/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/opt/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/flask/cli.py", line 256, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/opt/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/opt/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/flask/cli.py", line 90, in locate_app
    __import__(module)
  File "/opt/PowerDNS-Admin/app/__init__.py", line 109, in <module>
    from app import views, models
  File "/opt/PowerDNS-Admin/app/views.py", line 20, in <module>
    from .models import User, Account, Domain, Record, Server, History, Anonymous, Setting, DomainSetting, DomainTemplate, DomainTemplateRecord
  File "/opt/PowerDNS-Admin/app/models.py", line 16, in <module>
    from urllib.parse import urljoin
ImportError: No module named parse

**Comment by electron79** [comment]
Reboot the server, then install "pip install parse", "pipe install -r requirements.txt".

Please follow the steps...

I am on step "flask assets build":

Building bundle: generated/login.css
[INFO] Building bundle: generated/login.css
Building bundle: generated/main.js
[INFO] Building bundle: generated/main.js
Building bundle: generated/main.css
[INFO] Building bundle: generated/main.css
[INFO] Building bundle: generated/main.css
Building bundle: generated/login.js
[INFO] Building bundle: generated/login.js

I thing so, that is ok. of moment...

**Comment by electron79** [comment]
PowerDNS-Admin no run !!!

This is my active conections:
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      778/pdns_server     
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      778/pdns_server     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      648/sshd            
tcp        0    196 192.168.2.240:22        192.168.2.43:51526      ESTABLISHED 803/sshd: root@pts/ 
tcp6       0      0 :::3306                 :::*                    LISTEN      744/mysqld          
tcp6       0      0 :::80                   :::*                    LISTEN      746/apache2         
tcp6       0      0 :::53                   :::*                    LISTEN      778/pdns_server     
tcp6       0      0 :::22                   :::*                    LISTEN      648/sshd            
udp        0      0 127.0.0.1:53            0.0.0.0:*                           778/pdns_server     
udp        0      0 0.0.0.0:16525           0.0.0.0:*                           778/pdns_server     
udp6       0      0 :::14040                :::*                                778/pdns_server     
udp6       0      0 :::53                   :::*                                778/pdns_server

**Comment by electron79** [comment]
./run.py
Traceback (most recent call last):
  File "./run.py", line 2, in <module>
    from app import app
  File "/opt/PowerDNS-Admin/app/__init__.py", line 1, in <module>
    from werkzeug.contrib.fixers import ProxyFix
ImportError: No module named 'werkzeug'

Reboot the server, then install "pip install parse", "pip install werkzeug", "pipe install -r requirements.txt".
Please follow the steps...

Modify the file config.py "bind_address":
nano config.py

# BASIC APP CONFIG
WTF_CSRF_ENABLED = True
SECRET_KEY = 'We are the world'
BIND_ADDRESS = '0.0.0.0'
PORT = 9191
LOGIN_TITLE = "PDNS"


Then you try run ./run.py
Of moment my server is running via web... But other error "The server refused to process your request and return a 400 error."
