### ISSUE TITLE
SAML Attribute Error 'function' object has no attribute 'urlparse'

### ISSUE THREAD

**Issue by MaxDiOrio** [ngoduykhanh/PowerDNS-Admin#308]
I'm trying to get ADFS/SAML working (would be nice if there was a Wiki article on this :)  )

I'm running on RHEL 7.4 using Nginx and gunicorn.

After enabling SAML and click on the SAML logon link on the home page, I get a 500 error the browser and the following error in the logs:

```
gunicorn: [2018-07-16 10:58:31,739] ERROR in app: Exception on /saml/login [GET]
gunicorn: Traceback (most recent call last):
gunicorn: File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
gunicorn: response = self.full_dispatch_request()
gunicorn: File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
gunicorn: rv = self.handle_user_exception(e)
gunicorn: File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
gunicorn: reraise(exc_type, exc_value, tb)
gunicorn: File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
gunicorn: raise value
gunicorn: File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
gunicorn: rv = self.dispatch_request()
gunicorn: File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
gunicorn: return self.view_functions[rule.endpoint](**req.view_args)
gunicorn: File "/opt/web/powerdns-admin/app/views.py", line 191, in saml_login
gunicorn: req = utils.prepare_flask_request(request)
gunicorn: File "/opt/web/powerdns-admin/app/lib/utils.py", line 208, in prepare_flask_request
gunicorn: url_data = urlparse.urlparse(request.url)
gunicorn: AttributeError: 'function' object has no attribute 'urlparse'
```

**Comment by ngoduykhanh** [comment]
It is the issue created when we migrate the code from python2 to python3. Should be fixed in #255 i believe. Can you help to give a try on that PR?

**Comment by rodehoed** [comment]
@MaxDiOrio :+1: for a wiki

**Comment by B3DTech** [comment]
Sorry... Didn't get notification about the post. I'll test it out when I get back to work Thursday.

**Comment by rodehoed** [comment]
@ngoduykhanh the error is gone when pulling PR #255

**Comment by ngoduykhanh** [comment]
Nice! I merged the PR to master. Thanks for doing the test.
