### ISSUE TITLE
SAML  Invalid dict settings: idp_sso_not_found error

### ISSUE THREAD

**Issue by rodehoed** [ngoduykhanh/PowerDNS-Admin#322]
Hi,

With PR #255 active i'm getting an cryptic exception:

```
Traceback (most recent call last):
  File "<path>VirtualENV/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "<path>VirtualENV/lib/python3.5/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "<path>VirtualENV/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "<path>VirtualENV/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<path>VirtualENV/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "<path>VirtualENV/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "<path>VirtualENV/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "<path>VirtualENV/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "<path>VirtualENV/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "<path>VirtualENV/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "<path>VirtualENV/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<path>src/app/views.py", line 192, in saml_login
    auth = utils.init_saml_auth(req)
  File "<path>src/app/lib/utils.py", line 280, in init_saml_auth
    auth = OneLogin_Saml2_Auth(req, settings)
  File "<path>VirtualENV/lib/python3.5/site-packages/onelogin/saml2/auth.py", line 54, in __init__
    self.__settings = OneLogin_Saml2_Settings(old_settings, custom_base_path)
  File "<path>VirtualENV/lib/python3.5/site-packages/onelogin/saml2/settings.py", line 114, in __init__
    ','.join(self.__errors)
onelogin.saml2.errors.OneLogin_Saml2_Error: Invalid dict settings: idp_sso_not_found
```
I parsed/validated the federated metadata XML coming from the idp provider and it's valid.
When I remove the metadata file i'm getting an 404 exception. Just wanted to be sure that the metadata is downloaded. 

This is my config(slightly anonymised):

```
SAML_ENABLED = True
SAML_DEBUG = True
SAML_PATH = os.path.join(os.path.dirname(__file__), 'saml')
SAML_METADATA_URL = 'https://<redacted>/SAML/SAML-Poweradmin-Federation.xml'
SAML_METADATA_CACHE_LIFETIME = 1
SAML_ATTRIBUTE_EMAIL = 'urn:oid:0.9.2342.19200300.100.1.3'
SAML_ATTRIBUTE_ADMIN = 'just-bogus'
SAML_ATTRIBUTE_ACCOUNT = 'https://example.edu/pdns-account'
SAML_SP_ENTITY_ID = 'poweradminSP'
SAML_SP_CONTACT_NAME = '<me>'
SAML_SP_CONTACT_MAIL = '<me>'
SAML_SIGN_REQUEST = False
SAML_LOGOUT = False
```

Im willing to help with access to an IDP account.

**Comment by icb-** [comment]
`idp_sso_not_found` seems to indicate that the metadata was found, but that it doesn't include any `SingleSignOnService`. OneLogin SAML2 [settings.py](https://github.com/onelogin/python-saml/blob/2b283b5568e67d8139f46ad8e7426d4f37172d86/src/onelogin/saml2/settings.py#L354-L355) code reference

**Comment by rodehoed** [comment]
Hi @icb- 

I checked the XML file and the SingleSignOnService seems to be there. This is my metatadata file:

```
<?xml version="1.0" encoding="UTF-8"?>
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="<remove for privacy>">
  <md:IDPSSODescriptor WantAuthnRequestsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <md:KeyDescriptor use="signing">
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
          <ds:X509Certificate><removed for privacy></ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </md:KeyDescriptor>
    <md:NameIDFormat>urn:oasis:names:tc:SAML:1.0:nameid-format:unspecified</md:NameIDFormat>
    <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://sso.jumpcloud.com/xxxxxxxx"/>
  </md:IDPSSODescriptor>
</md:EntityDescriptor>
```

**Comment by icb-** [comment]
You only have a `SingleSignOnService` of type `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST`. One of type `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect` is required for it to work (and I believe required by specification.)

**Comment by rodehoed** [comment]
Hi @icb- ,

Ok I think it's good to check  if the problem is in the SAML implementation of powerdns admin or that my input is not correct (and thus this bugreport is not valid).

This is the metadata is coming directly from jumpcloud, a dedicated directory-service-as-a-service. I have tested with an php application (using the php class from Onelogin) and it works. 

If i'm correct the HTTP-Redirect binding you talking about is called the so called Redirect Endpoint option which should be an optional option and only needed when the SP requires it.

I would like to test some things. But just to be sure, what the ACS (Assertion Consumer Service) should I use (just the path eg. /saml/login)?

**Comment by icb-** [comment]
@rodehoed Try the referenced branch on my fork. You should be able to apply that and set `SAML_IDP_SSO_BINDING = 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'` in your config to have it use the `HTTP-POST` binding format.

According to the metadata I get from my test install at `/saml/metadata`, the ACS is `https://<host>/saml/authorized`.

**Comment by rodehoed** [comment]
Good morning @icb- 

Thanks for the fix, it works well :+1:  But getting an SAML Authentication Error on /saml/authorized telling me invalid_reponse (console says:  "There is no AttributeStatement on the Response"). Willing to share you (redacted) metadata xml? I would like to compare it with the one coming from JC.

If I get the parts together I will try to make a wiki page for it so it might save some extra "bug" reports.

**Comment by rodehoed** [comment]
Seems because the strict mode is on. Setting it to False seems to make stuff works!

**Comment by icb-** [comment]
Pretty standard metadata for a Shibboleth IdP (the IdP software I'm running). Your last error is because the SAML `Response` is missing an `AttributeStatement`. If clearing strict mode fixes that, then it sounds like a reasonable fix for you.

Redacted (and otherwise massaged) metadata and SAML `Response` below.

```xml
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata"
                  xmlns:shibmd="urn:mace:shibboleth:metadata:1.0"
                  xmlns:mdui="urn:oasis:names:tc:SAML:metadata:ui"
                  xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
                  entityID="https://example.edu/idp/shibboleth">
  <IDPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <Extensions>
      <shibmd:Scope regexp="false">example.edu.edu</shibmd:Scope>
      <mdui:UIInfo>
        <mdui:DisplayName xml:lang="en">Example</mdui:DisplayName>
        <mdui:Description xml:lang="en">
          The Identity Provider for Example
        </mdui:Description>
        <mdui:Logo height="200" width="300" xml:lang="en">
          https://picsum.photos/300/200
        </mdui:Logo>
      </mdui:UIInfo>
    </Extensions>
    <KeyDescriptor use="signing">
      <ds:KeyInfo>
        <ds:X509Data>
          <ds:X509Certificate>MIIBOzCB46ADAgECAgEBMAoGCCqGSM49BAMCMAAwHhcNMTgwODA1MTU1NTQzWhcN
            MjgwODAzMTU1NTQzWjAAMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAElwjBx4Jm
            KepYF2ly98NEQC9Bhuoa7R05bOgYyfuESVLrt8+dv0yJ/uZrf+RUJjHqZg0VW74l
            wkTYJBRB/C6+MaNOMEwwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUF
            BwMBMAwGA1UdEwEB/wQCMAAwFwYDVR0RAQH/BA0wC4IJbG9jYWxob3N0MAoGCCqG
            SM49BAMCA0cAMEQCIAVTYYVkCpJUQJky1YkIkqZ5tkbolu7vvU8nuVy1LMnYAiAw
            nBVDG9sAaeHusb9bS+tcQzP37zp8hXFMxLAMojGgJw==</ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </KeyDescriptor>
    <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://idp.example.edu/idp/profile/Logout"/>
    <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://idp.example.edu/idp/profile/SAML2/Redirect/SSO"/>
    <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://idp.example.edu/idp/profile/SAML2/POST/SSO"/>
  </IDPSSODescriptor>
  <Organization>
    <OrganizationName xml:lang="en">Example</OrganizationName>
    <OrganizationDisplayName xml:lang="en">Example</OrganizationDisplayName>
    <OrganizationURL xml:lang="en">https://example.edu/</OrganizationURL>
  </Organization>
  <ContactPerson contactType="support">
    <GivenName>Support</GivenName>
    <EmailAddress>support@example.edu</EmailAddress>
  </ContactPerson>
  <ContactPerson contactType="technical">
    <GivenName>Tech</GivenName>
    <EmailAddress>support@example.edu</EmailAddress>
  </ContactPerson>
  <ContactPerson contactType="administrative">
    <GivenName>Admin</GivenName>
    <EmailAddress>support@example.edu</EmailAddress>
  </ContactPerson>
</EntityDescriptor>
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<saml2p:Response Destination="https://dns.example.edu/saml/authorized"
    ID="_b1fbbbba826386b95d00a82cd5a61352"
    InResponseTo="_a1e21e9f529f28006d2d22035fd32f136f696d97faf0f38611cd1c45e79903f0"
    IssueInstant="2018-08-09T11:57:57.211Z" Version="2.0"
    xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol">
    <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">https://idp.example.edu/idp/shibboleth</saml2:Issuer>
        <saml2:Subject>
            <saml2:NameID Format="urn:oid:0.9.2342.19200300.100.1.1"
                NameQualifier="https://idp.example.edu/idp/shibboleth"
                SPNameQualifier="https://dns.example.edu">me</saml2:NameID>
            <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml2:SubjectConfirmationData Address="192.0.2.0"
                InResponseTo="_a1e21e9f529f28006d2d22035fd32f136f696d97faf0f38611cd1c45e79903f0"
                NotOnOrAfter="2018-08-09T12:02:57.219Z" Recipient="https://dns.example.edu/saml/authorized"/></saml2:SubjectConfirmation>
        </saml2:Subject>
        <saml2:Conditions NotBefore="2018-08-09T11:57:57.211Z" NotOnOrAfter="2018-08-09T12:02:57.211Z">
            <saml2:AudienceRestriction>
                <saml2:Audience>https://dns.example.edu</saml2:Audience>
            </saml2:AudienceRestriction>
        </saml2:Conditions>
        <saml2:AuthnStatement AuthnInstant="2018-08-09T11:57:57.064Z"
            SessionIndex="_d728ea655b9a2659dfe699c65f9d2aa8"><saml2:SubjectLocality Address="192.0.2.0"/>
            <saml2:AuthnContext>
                <saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml2:AuthnContextClassRef>
            </saml2:AuthnContext>
        </saml2:AuthnStatement>
        <saml2:AttributeStatement>
            <saml2:Attribute FriendlyName="uid" Name="urn:oid:0.9.2342.19200300.100.1.1"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue>me</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="mail" Name="urn:oid:0.9.2342.19200300.100.1.3"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue>me@example.edu</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="displayName" Name="urn:oid:2.16.840.1.113730.3.1.241"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue>Me</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="eduPersonPrincipalName" Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.6"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue>me@example.edu</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="administrator" Name="https://dns.example.edu/admin"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue>true</saml2:AttributeValue>
            </saml2:Attribute>
        </saml2:AttributeStatement>
    </saml2:Assertion>
</saml2p:Response>
```

**Comment by icb-** [comment]
On further review, disabling `strict` is [insecure](https://github.com/onelogin/python3-saml/#security-warning).
