### ISSUE TITLE
Centos7 Installation Steps

### ISSUE THREAD

**Issue by simhaonline** [ngoduykhanh/PowerDNS-Admin#336]
cd /home && git clone https://github.com/ngoduykhanh/PowerDNS-Admin.git pdns-admin
cd pdns-admin
pip3.6 install --upgrade setuptools
pip3.6 install -r requirements.txt
npm install
yarn install

export FLASK_APP=/home/pdns-admin/app/__init__.py
export DB_MIGRATION_DIR=/home/pdns-admin/migrations
export FLASK_ENV=development 

cp /home/pdns-admin/configs/development.py /home/pdns-admin/config.py

flask db init --directory ${DB_MIGRATION_DIR}
flask db migrate -m "Init DB" --directory ${DB_MIGRATION_DIR}
flask db upgrade --directory ${DB_MIGRATION_DIR}
./init_data.py
flask db migrate -m "Upgrade BD Schema" --directory ${DB_MIGRATION_DIR}
flask db upgrade --directory ${DB_MIGRATION_DIR}
  
chown -R www-data:www-data /home/powerdns-admin/app/static
chown -R www-data:www-data /home/powerdns-admin/node_modules
su -s /bin/bash -c 'yarn install --pure-lockfile' www-data

chown -R www-data:www-data /home/powerdns-admin/logs
su -s /bin/bash -c 'flask assets build' www-data

flask run

But at time of migration i am getting error

flask db init --directory ${DB_MIGRATION_DIR}
Traceback (most recent call last):
  File "/usr/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/usr/lib/python3.6/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask/cli.py", line 256, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/lib/python3.6/site-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/usr/lib/python3.6/site-packages/flask/cli.py", line 90, in locate_app
    __import__(module)
  File "/home/pdns-admin/app/__init__.py", line 18, in <module>
    app.config.from_object('config')
  File "/usr/lib/python3.6/site-packages/flask/config.py", line 168, in from_object
    obj = import_string(obj)
  File "/usr/lib/python3.6/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/home/pdns-admin/config.py", line 23, in <module>
    SQLALCHEMY_DATABASE_URI = 'mysql://'+DB_USER+':'+DB_PASSWORD+'@'+DB_HOST+'/'+DB_NAME
TypeError: must be str, not NoneType

Please advice

**Comment by ngoduykhanh** [comment]
Please use `config_template.py` file for the sample configuration. You can also take a look at Installation guide for CentOS at wiki page.

**Comment by simhaonline** [comment]
Thanks for your prompt response.
