### ISSUE TITLE
add domain type issue

### ISSUE THREAD

**Issue by vpotap** [ngoduykhanh/PowerDNS-Admin#340]
get error after trying to configure powerdns in slave mode , powerdns + admin run in docker

Traceback (most recent call last):
  File "/usr/share/webapps/powerdns-admin/app/models.py", line 599, in add
    jdata = utils.fetch_json(urlparse.urljoin(PDNS_STATS_URL, API_EXTENDED_URL + '/servers/localhost/zones'), headers=headers, method='POST', data=post_data)
  File "/usr/share/webapps/powerdns-admin/app/lib/utils.py", line 64, in fetch_json
    r = fetch_remote(remote_url, method=method, data=data, params=params, headers=headers, accept='application/json; q=1')
  File "/usr/share/webapps/powerdns-admin/app/lib/utils.py", line 52, in fetch_remote
    params=params
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)

**Comment by ngoduykhanh** [comment]
Hi,

What do you mean by  Slave mode here? How did you run PDA with docker? We used Python 3 but your log shows python 2.7.
