### ISSUE TITLE
Centos7/MariaDB Installation failed

### ISSUE THREAD

**Issue by rdeimling** [ngoduykhanh/PowerDNS-Admin#363]
I am following the wiki's install document but for MariaDB. In the guide, it says the dependencies will be different for MariaDB but it doesn't say what they are. Anyway, I got all the way down to the line where you are running pip install -r requirements.txt and I get a failure at the collecting mysqlclient portion. I went through some of the other issues and saw someone fixed it in debian by downloading a lib but it didnt work on Centos7.

```
Collecting SQLAlchemy==1.2.5 (from -r requirements.txt (line 7)) 

  Using cached https://files.pythonhosted.org/packages/7e/57/435347429f4ff5016b72c9b179c70a6cc67e5f9b4d3f3e9b51362c40b356/SQLAlchemy-1.2.5.tar.gz 

Collecting mysqlclient==1.3.12 (from -r requirements.txt (line 8)) 

  Using cached https://files.pythonhosted.org/packages/6f/86/bad31f1c1bb0cc99e88ca2adb7cb5c71f7a6540c1bb001480513de76a931/mysqlclient-1.3.12.tar.gz 

    Complete output from command python setup.py egg_info: 

    /bin/sh: mysql_config: command not found 

    Traceback (most recent call last): 

      File "<string>", line 1, in <module> 

      File "/tmp/pip-install-tgppvvp8/mysqlclient/setup.py", line 17, in <module> 

        metadata, options = get_config() 

      File "/tmp/pip-install-tgppvvp8/mysqlclient/setup_posix.py", line 44, in get_config 

        libs = mysql_config("libs_r") 

      File "/tmp/pip-install-tgppvvp8/mysqlclient/setup_posix.py", line 26, in mysql_config 

        raise EnvironmentError("%s not found" % (mysql_config.path,)) 

    OSError: mysql_config not found 

  

    ---------------------------------------- 

Command "python setup.py egg_info" failed with error code 1 in **/tmp/pip-install-tgppvvp8/mysqlclient/**
 
```

**Comment by rdeimling** [comment]
So I was reading an install document for another UI and it gave me some dependencies. So for anyone who is using MariaDB, you will need to do yum install MariaDB-devel.

I am still getting errors though, but I will work through those before closing this case.

**Comment by rdeimling** [comment]
The remaining errors were just more dependencies. This time they were listed. Hopefully, more dependencies besides just mysql can be listed in the documents to make this install easier.
