### ISSUE TITLE
Ubuntu 16.04 install problems.

### ISSUE THREAD

**Issue by cwray** [ngoduykhanh/PowerDNS-Admin#369]
### Problem one.
 
Yarn repo install commands are wrong. 

Current.
```
$ sudo curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
$ sudo echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
```

Should be.
```
sudo curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
```

### Problem two.
Virtualenv is not in the list of required packges.

### Problem three.
pip packages ```config & python-dotenv & werkzeug''' are not installed by requirements.text

(flask) me@dns:/opt/PowerDNS-Admin# flask db upgrade
 * Tip: There are .env files present. Do "pip install python-dotenv" to use them.
Usage: flask db upgrade [OPTIONS] [REVISION]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/opt/PowerDNS-Admin/flask/lib/python3.5/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
ImportError: No module named 'config'
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/PowerDNS-Admin/flask/lib/python3.5/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/opt/PowerDNS-Admin/app/__init__.py", line 19, in <module>
    app.config.from_object('config')
  File "/opt/PowerDNS-Admin/flask/lib/python3.5/site-packages/flask/config.py", line 170, in from_object
    obj = import_string(obj)
  File "/opt/PowerDNS-Admin/flask/lib/python3.5/site-packages/werkzeug/utils.py", line 443, in import_string
    sys.exc_info()[2])
  File "/opt/PowerDNS-Admin/flask/lib/python3.5/site-packages/werkzeug/_compat.py", line 137, in reraise
    raise value.with_traceback(tb)
  File "/opt/PowerDNS-Admin/flask/lib/python3.5/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
werkzeug.utils.ImportStringError: import_string() failed for 'config'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- config not found.

**Comment by cwray** [comment]
This configuration https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/uWSGI-example also fails.

Mon Sep 24 21:13:57 2018 - Set PythonHome to /opt/PowerDNS-Admin/flask
ImportError: No module named site

**Comment by wolkenbauer** [comment]
I have the same issue as @cwray and no idea what could be wrong.
