### ISSUE TITLE
Upgrade procedure for wiki

### ISSUE THREAD

**Issue by prupert** [ngoduykhanh/PowerDNS-Admin#424]
There is currently no documentation on the wiki regarding the update procedure. I figure it should be something along the lines of:

```
cd /path/to/powerdns-admin
git pull
source ./flask/bin/activate
pip install -r requirements.txt
export FLASK_APP=app/__init__.py
flask db upgrade
flask assets build
```

I am not sure if this is sufficient and if all commands are required for an update. Perhaps we can correct and annotate these instructions to create a wiki page.

**Comment by openmsk** [comment]
```
# flask db upgrade
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 787bdba9e147, Init DB
Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1050, "Table 'account' already exists")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/command.py", line 276, in upgrade
    script.run_env()
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/util/compat.py", line 156, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 88, in <module>
    run_migrations_online()
  File "migrations/env.py", line 81, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/runtime/migration.py", line 361, in run_migrations
    step.migration_fn(**kw)
  File "/opt/web/powerdns-admin/migrations/versions/787bdba9e147_init_db.py", line 74, in upgrade
    sa.PrimaryKeyConstraint('id')
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/operations/ops.py", line 1248, in create_table
    return operations.invoke(op)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/operations/base.py", line 345, in invoke
    return fn(self, operation)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/operations/toimpl.py", line 101, in create_table
    operations.impl.create_table(table)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/ddl/impl.py", line 251, in create_table
    self._exec(schema.CreateTable(table))
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1050, "Table 'account' already exists") [SQL: '\nCREATE TABLE account (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tname VARCHAR(40) NOT NULL, \n\tdescription VARCHAR(128), \n\tcontact VARCHAR(128), \n\tmail VARCHAR(128), \n\tPRIMARY KEY (id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/e3q8)
```

debug web page
```
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'domain.account_id' in 'field list'") [SQL: 'SELECT domain.id AS domain_id, domain.name AS domain_name, domain.master AS domain_master, domain.type AS domain_type, domain.serial AS domain_serial, domain.notified_serial AS domain_notified_serial, domain.last_check AS domain_last_check, domain.dnssec AS domain_dnssec, domain.account_id AS domain_account_id \nFROM domain'] (Background on this error at: http://sqlalche.me/e/e3q8)

```

```
# mysql -u $U -p$P powerdns --execute="SELECT * from domain;"
+-----+--------------------------------+--------+--------+------------+-----------------+------------+--------+
| id  | name                           | master | type   | serial     | notified_serial | last_check | dnssec |
+-----+--------------------------------+--------+--------+------------+-----------------+------------+--------+
|   3 | domain.ru                      | []     | Native | 2017032103 |      2017032103 |          0 |      0 |


# mysql -u $U -p$P powerdns --execute="show tables;"
+--------------------+
| Tables_in_powerdns |
+--------------------+
| account            |
| alembic_version    |
| comments           |
| cryptokeys         |
| domain             |
| domain_setting     |
| domain_template    |
| domain_user        |
| domainmetadata     |
| domains            |
| history            |
| migrate_version    |
| migrations         |
| perm_items         |
| perm_templ         |
| perm_templ_items   |
| records            |
| records_zone_templ |
| role               |
| setting            |
| supermasters       |
| tsigkeys           |
| user               |
| users              |
| zone_templ         |
| zone_templ_records |
| zones              |
+--------------------+
[root@ns1 ~]# mysql -u $U -p$P powerdns --execute="SELECT * from account;"

```

**Comment by Ramalama2** [comment]
you can make an update script for example:

1. make first a directory, lets call it backup:
mkdir /root/backup-pdns-admin

2. make a script (to get it little bit easier):
/root/update-pdns-admin.sh
```
#!/bin/bash
/usr/bin/systemctl stop powerdns-admin
cp -f /opt/web/powerdns-admin/config.py /root/backup-pdns-admin/config.py
cp -r /opt/web/powerdns-admin/upload/avatar /root/backup-pdns-admin/
rm -rf /opt/web/powerdns-admin
git clone https://github.com/ngoduykhanh/PowerDNS-Admin.git /opt/web/powerdns-admin
cp -f /root/backup-pdns-admin/config.py /opt/web/powerdns-admin/config.py
cp -f /root/backup-pdns-admin/avatar/* /opt/web/powerdns-admin/upload/avatar/
```


3. execute all the other commands (this doesn't work in a script, thats why you need to do it yourself):
```
# cd /opt/web/powerdns-admin/
# virtualenv -p python3 flask
# . ./flask/bin/activate
# pip install python-dotenv
# pip install -r requirements.txt
# export FLASK_APP=app/__init__.py
# flask db upgrade
# yarn install --pure-lockfile
# flask assets build
# deactivate
# systemctl restart powerdns-admin
```

Thats how i do it everytime, and it works perfect every time...

Im using Python 3.6 with nginx and a systemctl service (Check the wiki)
https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Centos-7

Would be great to combine all that commands into a script, but i found no way to get virtualenv working in the script :-(

@openmsk 
Your Problem is, something went wrong in the update procedure, thats why "flask db upgrade" doesnt work for you...
I had the exact same issue, some time ago... My Problem was, that i didnt knowed exactly how to update and somehow destroyed powerdns-admin, i tryed to update multiple times in a wrong way...

However,
1. you can try to backup your config.py and the avatar directory, (check your config.py first with the config_template.py (maybe something changed))
2. delete the whole powerdns-admin directory, clone it again, replace the config.py and avatar directory.
3. execute the commands from step 3. above...

Cheers :-)

**Comment by openmsk** [comment]
Hello, Ramalama2
I installed new Ubuntu 18.04, installed pdns-server, pdns-backend-mysql, mariadb-server, and powerdns-admin
```
mysql -u pdns -p powerdns < /usr/share/doc/pdns-backend-mysql/schema.mysql.sql
(flask)# flask db upgrade
<skip>
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1050, "Table 'account' already exists") [SQL: '\nCREATE TABLE account (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tname VARCHAR(40) NOT NULL, \n\tdescription VARCHAR(128), \n\tcontact VARCHAR(128), \n\tmail VARCHAR(128), \n\tPRIMARY KEY (id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/e3q8)

##mysql -u pdns -p powerdns -e 'DROP TABLE account;' 
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1050, "Table 'domain_template' already exists") [SQL: '\nCREATE TABLE domain_template (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tname VARCHAR(255), \n\tdescription VARCHAR(255), \n\tPRIMARY KEY (id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/e3q8)

##mysql -u pdns -p powerdns -e 'DROP TABLE account;DROP TABLE domain_template;' 
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1071, 'Specified key was too long; max key length is 767 bytes') [SQL: 'CREATE UNIQUE INDEX ix_domain_template_name ON domain_template (name)'] (Background on this error at: http://sqlalche.me/e/e3q8)

```
What to do next? how to solve a problem?

**Comment by alsyundawy** [comment]
up

**Comment by jbe-dw** [comment]
Hello @alsyundawy please open a new issue with a question regarding your difficulties.

Regards

**Comment by alsyundawy** [comment]
same case no need open new issue

**Comment by loopguard404** [comment]
Since I have Oracle8 and pgsql I did this:

systemctl stop powerdns-admin.socket
systemctl stop powerdns-admin.service
cp -f /opt/powerdns-admin/powerdnsadmin/default_config.py /home/%user%/default_config.py
rm -rf /opt/powerdns-admin
git clone https://github.com/ngoduykhanh/PowerDNS-Admin.git /opt/powerdns-admin
cp -f /home/%user%/default_config.py /opt/powerdns-admin/powerdnsadmin/default_config.py
cd /opt/powerdns-admin/
virtualenv -p python3 flask
. ./flask/bin/activate
pip install python-dotenv
remove mysqlclient and add psycopg2 requirements.txt
pip install -r requirements.txt
export FLASK_APP=powerdnsadmin/__init__.py
flask db upgrade
yarn install --pure-lockfile
flask assets build
deactivate
systemctl restart powerdns-admin.socket
systemctl restart powerdns-admin.service


when executing the export FLASK_APP item, specify the name of the folder where the project itself is located. Ramalama2 has this app, I have powerdnsadmin, pay attention to this.

Sorry for my english, maybe it will help someone
