### ISSUE TITLE
Latest PowerDNS, domain with lots of records, IndexError?

### ISSUE THREAD

**Issue by devinacosta** [ngoduykhanh/PowerDNS-Admin#439]
I have installed PowerDNS-Admin and got it working, however when I click on a domain that has quite a  bit of records, it errors out on me.

[INFO] 10.233.231.30 - - [14/Jan/2019 14:07:49] "GET /domain/owteam.com HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/opt/web/powerdns-admin/app/decorators.py", line 47, in decorated_function
    return f(*args, **kwargs)
  File "/opt/web/powerdns-admin/app/views.py", line 612, in domain
    zone_info = r.get_record_data(domain.name)
  File "/opt/web/powerdns-admin/app/models.py", line 1322, in get_record_data
    rrset['content'] = rrset['records'][0]['content']
IndexError: list index out of range
[INFO] 10.233.231.30 - - [14/Jan/2019 14:07:49] "GET /domain/owteam.com?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[INFO] 10.233.231.30 - - [14/Jan/2019 14:07:49] "GET /domain/owteam.com?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
[INFO] 10.233.231.30 - - [14/Jan/2019 14:07:49] "GET /domain/owteam.com?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
[INFO] 10.233.231.30 - - [14/Jan/2019 14:07:50] "GET /domain/owteam.com?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
[INFO] 10.233.231.30 - - [14/Jan/2019 14:07:50] "GET /domain/owteam.com?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[INFO] 10.233.231.30 - - [14/Jan/2019 14:07:50] "GET /domain/owteam.com?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

**Comment by rkerr** [comment]
How many records does the domain have? I would guess the error is being cause by the powerdns API returning a RRSet object with no records in it, but it's not clear to me how that could happen. It's probably more likely to be something in the zone triggering it rather than the size.

**Comment by rkerr** [comment]
Possibly the same issue as #421 - does the zone have comments?
