### ISSUE TITLE
StrictVersion() is too strict :)

### ISSUE THREAD

**Issue by goldyfruit** [ngoduykhanh/PowerDNS-Admin#481]
Hi,

I currently using PowerDNS `4.2.0-beta1` but PowerDNS-Admin doesn't handle it properly, the `-` is not supported by `StrictVersion()`.

```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/opt/PowerDNS-Admin/app/views.py", line 645, in dashboard
    Domain().update()
  File "<string>", line 4, in __init__
  File "/opt/venv/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 417, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/opt/venv/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/opt/venv/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/opt/PowerDNS-Admin/app/models.py", line 846, in __init__
    self.API_EXTENDED_URL = utils.pdns_api_extended_uri(self.PDNS_VERSION)
  File "/opt/PowerDNS-Admin/app/lib/utils.py", line 200, in pdns_api_extended_uri
    if StrictVersion(version) >= StrictVersion('4.0.0'):
  File "/usr/lib/python3.5/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib/python3.5/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '4.2.0-beta1'
```

Thanks for you help :)

**Comment by ngoduykhanh** [comment]
I think you can just put 4.2.0 in config. The purpose of using StrictVersion is to split the API of PNS v3 and v4 only, for the major version of v4, there is no difference atm.

**Comment by goldyfruit** [comment]
@ngoduykhanh Thanks :)

**Comment by brianredbeard** [comment]
If not fixing the reported issue at the very least adding better error handling would greatly improve the UX.  Currently having a version number like the one reported by @goldyfruit causes most of the pages in the interface to return a 500 error:

![image](https://user-images.githubusercontent.com/57542/149604942-01f0ef26-49cc-4323-845d-f05ec8b426df.png)


I discovered this when testing the 4.6.0 release candidate which came out today:

```python

[2022-01-15 02:05:56,843] [app.py:1891] ERROR - Exception on /dashboard/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/powerdnsadmin/routes/dashboard.py", line 150, in dashboard
    Domain().update()
  File "<string>", line 4, in __init__
  File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/app/powerdnsadmin/models/domain.py", line 57, in __init__
    self.API_EXTENDED_URL = utils.pdns_api_extended_uri(self.PDNS_VERSION)
  File "/app/powerdnsadmin/lib/utils.py", line 182, in pdns_api_extended_uri
    if StrictVersion(version) >= StrictVersion('4.0.0'):
  File "/usr/lib/python3.8/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib/python3.8/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '4.6.0-rc1'
```
