### ISSUE TITLE
minikube: docker-compose up: "ERROR 1130 (HY000): Host is not allowed to connect to this MySQL server"

### ISSUE THREAD

**Issue by bitsofinfo** [ngoduykhanh/PowerDNS-Admin#504]
Just following the example in the README

I am using Minikube

"ERROR 1130 (HY000): Host is not allowed to connect to this MySQL server"

```
bash-4.4$ eval $(minikube docker-env)
bash-4.4$ source .env
bash-4.4$ docker-compose up
Creating network "powerdns-admin_default" with the default driver
Creating pdns-mysql           ... done
Creating powerdns-admin-mysql ... done
Creating powerdns-admin_pdns-server_1 ... done
Creating powerdns-admin               ... done
Attaching to pdns-mysql, powerdns-admin-mysql, powerdns-admin_pdns-server_1, powerdns-admin
pdns-mysql              | [Entrypoint] MySQL Docker Image 5.7.26-1.1.11
powerdns-admin-mysql    | [Entrypoint] MySQL Docker Image 5.7.26-1.1.11
pdns-server_1           | Waiting for database to come up
powerdns-admin          | ===> Waiting for powerdns-admin-mysql MySQL service
powerdns-admin          | DNS fwd/rev mismatch: powerdns-admin-mysql != powerdns-admin-mysql.powerdns-admin_default
powerdns-admin          | powerdns-admin-mysql [172.22.0.3] 3306 (mysql) open
powerdns-admin          | ===> DB management
powerdns-admin          | ---> Running DB Migration
powerdns-admin          |  * Tip: There are .env files present. Do "pip install python-dotenv" to use them.
powerdns-admin          | Traceback (most recent call last):
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
powerdns-admin          |     return fn()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 345, in unique_connection
powerdns-admin          |     return _ConnectionFairy._checkout(self)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 784, in _checkout
powerdns-admin          |     fairy = _ConnectionRecord.checkout(pool)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 532, in checkout
powerdns-admin          |     rec = pool._do_get()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1280, in _do_get
powerdns-admin          |     return self._create_connection()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 350, in _create_connection
powerdns-admin          |     return _ConnectionRecord(self)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 477, in __init__
powerdns-admin          |     self.__connect(first_connect_check=True)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 667, in __connect
powerdns-admin          |     connection = pool._invoke_creator(self)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/strategies.py", line 106, in connect
powerdns-admin          |     return dialect.connect(*cargs, **cparams)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 410, in connect
powerdns-admin          |     return self.dbapi.connect(*cargs, **cparams)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/__init__.py", line 86, in Connect
powerdns-admin          |     return Connection(*args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 204, in __init__
powerdns-admin          |     super(Connection, self).__init__(*args, **kwargs2)
powerdns-admin          | _mysql_exceptions.OperationalError: (1130, "Host '172.22.0.5' is not allowed to connect to this MySQL server")
powerdns-admin          |
powerdns-admin          | The above exception was the direct cause of the following exception:
powerdns-admin          |
powerdns-admin          | Traceback (most recent call last):
powerdns-admin          |   File "/usr/local/bin/flask", line 11, in <module>
powerdns-admin          |     sys.exit(main())
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 894, in main
powerdns-admin          |     cli.main(args=args, prog_name=name)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 557, in main
powerdns-admin          |     return super(FlaskGroup, self).main(*args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
powerdns-admin          |     rv = self.invoke(ctx)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
powerdns-admin          |     return _process_result(sub_ctx.command.invoke(sub_ctx))
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
powerdns-admin          |     return _process_result(sub_ctx.command.invoke(sub_ctx))
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
powerdns-admin          |     return ctx.invoke(self.callback, **ctx.params)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
powerdns-admin          |     return callback(*args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
powerdns-admin          |     return f(get_current_context(), *args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 412, in decorator
powerdns-admin          |     return __ctx.invoke(f, *args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
powerdns-admin          |     return callback(*args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask_migrate/cli.py", line 90, in migrate
powerdns-admin          |     rev_id, x_arg)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask_migrate/__init__.py", line 95, in wrapped
powerdns-admin          |     f(*args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask_migrate/__init__.py", line 215, in migrate
powerdns-admin          |     version_path=version_path, rev_id=rev_id)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/alembic/command.py", line 197, in revision
powerdns-admin          |     script_directory.run_env()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/alembic/script/base.py", line 475, in run_env
powerdns-admin          |     util.load_python_file(self.dir, "env.py")
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/alembic/util/pyfiles.py", line 90, in load_python_file
powerdns-admin          |     module = load_module_py(module_id, path)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/alembic/util/compat.py", line 156, in load_module_py
powerdns-admin          |     spec.loader.exec_module(module)
powerdns-admin          |   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
powerdns-admin          |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
powerdns-admin          |   File "/powerdns-admin/migrations/env.py", line 88, in <module>
powerdns-admin          |     run_migrations_online()
powerdns-admin          |   File "/powerdns-admin/migrations/env.py", line 72, in run_migrations_online
powerdns-admin          |     connection = engine.connect()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2102, in connect
powerdns-admin          |     return self._connection_cls(self, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 90, in __init__
powerdns-admin          |     if connection is not None else engine.raw_connection()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2188, in raw_connection
powerdns-admin          |     self.pool.unique_connection, _connection)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
powerdns-admin          |     e, dialect, self)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
powerdns-admin          |     exc_info
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
powerdns-admin          |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
powerdns-admin          |     raise value.with_traceback(tb)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
powerdns-admin          |     return fn()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 345, in unique_connection
powerdns-admin          |     return _ConnectionFairy._checkout(self)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 784, in _checkout
powerdns-admin          |     fairy = _ConnectionRecord.checkout(pool)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 532, in checkout
powerdns-admin          |     rec = pool._do_get()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1280, in _do_get
powerdns-admin          |     return self._create_connection()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 350, in _create_connection
powerdns-admin          |     return _ConnectionRecord(self)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 477, in __init__
powerdns-admin          |     self.__connect(first_connect_check=True)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 667, in __connect
powerdns-admin          |     connection = pool._invoke_creator(self)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/strategies.py", line 106, in connect
powerdns-admin          |     return dialect.connect(*cargs, **cparams)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 410, in connect
powerdns-admin          |     return self.dbapi.connect(*cargs, **cparams)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/__init__.py", line 86, in Connect
powerdns-admin          |     return Connection(*args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 204, in __init__
powerdns-admin          |     super(Connection, self).__init__(*args, **kwargs2)
powerdns-admin          | sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1130, "Host '172.22.0.5' is not allowed to connect to this MySQL server") (Background on this error at: http://sqlalche.me/e/e3q8)
powerdns-admin          |  * Tip: There are .env files present. Do "pip install python-dotenv" to use them.
powerdns-admin          | Traceback (most recent call last):
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
powerdns-admin          |     return fn()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 345, in unique_connection
powerdns-admin          |     return _ConnectionFairy._checkout(self)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 784, in _checkout
powerdns-admin          |     fairy = _ConnectionRecord.checkout(pool)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 532, in checkout
powerdns-admin          |     rec = pool._do_get()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1280, in _do_get
powerdns-admin          |     return self._create_connection()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 350, in _create_connection
powerdns-admin          |     return _ConnectionRecord(self)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 477, in __init__
powerdns-admin          |     self.__connect(first_connect_check=True)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 667, in __connect
powerdns-admin          |     connection = pool._invoke_creator(self)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/strategies.py", line 106, in connect
powerdns-admin          |     return dialect.connect(*cargs, **cparams)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 410, in connect
powerdns-admin          |     return self.dbapi.connect(*cargs, **cparams)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/__init__.py", line 86, in Connect
powerdns-admin          |     return Connection(*args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 204, in __init__
powerdns-admin          |     super(Connection, self).__init__(*args, **kwargs2)
powerdns-admin          | _mysql_exceptions.OperationalError: (1130, "Host '172.22.0.5' is not allowed to connect to this MySQL server")
powerdns-admin          |
powerdns-admin          | The above exception was the direct cause of the following exception:
powerdns-admin          |
powerdns-admin          | Traceback (most recent call last):
powerdns-admin          |   File "/usr/local/bin/flask", line 11, in <module>
powerdns-admin          |     sys.exit(main())
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 894, in main
powerdns-admin          |     cli.main(args=args, prog_name=name)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 557, in main
powerdns-admin          |     return super(FlaskGroup, self).main(*args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
powerdns-admin          |     rv = self.invoke(ctx)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
powerdns-admin          |     return _process_result(sub_ctx.command.invoke(sub_ctx))
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
powerdns-admin          |     return _process_result(sub_ctx.command.invoke(sub_ctx))
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
powerdns-admin          |     return ctx.invoke(self.callback, **ctx.params)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
powerdns-admin          |     return callback(*args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
powerdns-admin          |     return f(get_current_context(), *args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 412, in decorator
powerdns-admin          |     return __ctx.invoke(f, *args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
powerdns-admin          |     return callback(*args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask_migrate/cli.py", line 134, in upgrade
powerdns-admin          |     _upgrade(directory, revision, sql, tag, x_arg)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask_migrate/__init__.py", line 95, in wrapped
powerdns-admin          |     f(*args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask_migrate/__init__.py", line 280, in upgrade
powerdns-admin          |     command.upgrade(config, revision, sql=sql, tag=tag)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/alembic/command.py", line 276, in upgrade
powerdns-admin          |     script.run_env()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/alembic/script/base.py", line 475, in run_env
powerdns-admin          |     util.load_python_file(self.dir, "env.py")
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/alembic/util/pyfiles.py", line 90, in load_python_file
powerdns-admin          |     module = load_module_py(module_id, path)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/alembic/util/compat.py", line 156, in load_module_py
powerdns-admin          |     spec.loader.exec_module(module)
powerdns-admin          |   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
powerdns-admin          |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
powerdns-admin          |   File "/powerdns-admin/migrations/env.py", line 88, in <module>
powerdns-admin          |     run_migrations_online()
powerdns-admin          |   File "/powerdns-admin/migrations/env.py", line 72, in run_migrations_online
powerdns-admin          |     connection = engine.connect()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2102, in connect
powerdns-admin          |     return self._connection_cls(self, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 90, in __init__
powerdns-admin          |     if connection is not None else engine.raw_connection()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2188, in raw_connection
powerdns-admin          |     self.pool.unique_connection, _connection)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
powerdns-admin          |     e, dialect, self)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
powerdns-admin          |     exc_info
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
powerdns-admin          |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
powerdns-admin          |     raise value.with_traceback(tb)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
powerdns-admin          |     return fn()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 345, in unique_connection
powerdns-admin          |     return _ConnectionFairy._checkout(self)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 784, in _checkout
powerdns-admin          |     fairy = _ConnectionRecord.checkout(pool)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 532, in checkout
powerdns-admin          |     rec = pool._do_get()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1280, in _do_get
powerdns-admin          |     return self._create_connection()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 350, in _create_connection
powerdns-admin          |     return _ConnectionRecord(self)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 477, in __init__
powerdns-admin          |     self.__connect(first_connect_check=True)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 667, in __connect
powerdns-admin          |     connection = pool._invoke_creator(self)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/strategies.py", line 106, in connect
powerdns-admin          |     return dialect.connect(*cargs, **cparams)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 410, in connect
powerdns-admin          |     return self.dbapi.connect(*cargs, **cparams)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/__init__.py", line 86, in Connect
powerdns-admin          |     return Connection(*args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 204, in __init__
powerdns-admin          |     super(Connection, self).__init__(*args, **kwargs2)
powerdns-admin          | sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1130, "Host '172.22.0.5' is not allowed to connect to this MySQL server") (Background on this error at: http://sqlalche.me/e/e3q8)
powerdns-admin          | ===> Update PDNS API connection info
powerdns-admin          | mysql: [Warning] Using a password on the command line interface can be insecure.
powerdns-admin          | ERROR 1130 (HY000): Host '172.22.0.5' is not allowed to connect to this MySQL server
powerdns-admin exited with code 1
pdns-server_1           | ERROR 1130 (HY000): Host '172.22.0.4' is not allowed to connect to this MySQL server
pdns-server_1           | ERROR 1130 (HY000): Host '172.22.0.4' is not allowed to connect to this MySQL server
pdns-server_1           | Waiting for database to come up
```

**Comment by bitsofinfo** [comment]
Note just using Docker for Mac, works, Minikube does not. Minikube is just another VM with Docker inside of it so not sure why its different.

**Comment by ngoduykhanh** [comment]
> ERROR 1130 (HY000): Host '172.22.0.4' is not allowed to connect to this MySQL server
It is the problem with MySQL privileges granting. I've never tried PDA with Minikute. Maybe you need to re-grant PDA mysql user to allow remote host access.
