### ISSUE TITLE
Error 500...

### ISSUE THREAD

**Issue by piwats** [ngoduykhanh/PowerDNS-Admin#51]
Somehow I cannot get PowerDNS-Admin to work under uwsgi.
The latest errors I get are like this one:

```
2016-06-26 15:23:13,887 - app - ERROR - Exception on /error/500 [GET]
Traceback (most recent call last):
  File "/PowerDNS-Admin/flask/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/PowerDNS-Admin/flask/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/PowerDNS-Admin/flask/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/PowerDNS-Admin/flask/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/PowerDNS-Admin/flask/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/PowerDNS-Admin/app/views.py", line 122, in error
    return render_template('errors/%s.html' % code, msg=msg), int(code)
  File "/PowerDNS-Admin/flask/lib/python2.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/PowerDNS-Admin/flask/lib/python2.7/site-packages/flask/app.py", line 765, in update_template_context
    context.update(func())
  File "/PowerDNS-Admin/app/views.py", line 27, in inject_fullscreen_layout_setting
    return dict(fullscreen_layout_setting=strtobool(fullscreen_layout_setting.value))
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by ngoduykhanh** [comment]
Problem was caused by the recent PR #50 . Please pull the latest update and run following command to update your powerdns admin database

```
insert into setting(name, value) values('fullscreen_layout', 'True');
insert into setting(name, value) values('record_helper', 'True');
insert into setting(name, value) values('default_record_table_size', 15);
```

**Comment by piwats** [comment]
I've reinitialized the db completely. It seems I get it to work again. But now I get this, when I try to load a domain:

```
2016-06-26 17:51:06,866 - app - ERROR - Exception on /domain/test.org [GET]
Traceback (most recent call last):
  File "/PowerDNS-Admin/flask/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/PowerDNS-Admin/flask/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/PowerDNS-Admin/flask/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/PowerDNS-Admin/flask/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/PowerDNS-Admin/flask/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/PowerDNS-Admin/flask/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/PowerDNS-Admin/app/views.py", line 245, in domain
    zone_info = r.get_record_data(domain.name)
  File "/PowerDNS-Admin/app/models.py", line 701, in get_record_data
    if NEW_SCHEMA:
NameError: global name 'NEW_SCHEMA' is not defined
```

**Comment by ngoduykhanh** [comment]
@piwats  Have you pulled the latest code?

**Comment by piwats** [comment]
Now it seems to work...
