### ISSUE TITLE
SAML integration problem - get_idp_data() is not defined

### ISSUE THREAD

**Issue by Neven1986** [ngoduykhanh/PowerDNS-Admin#601]
Hello,

it seems there is a problem with certain missing functions regarding SAML.
I'm trying to configure SAML, but when I enable it and set parameter "SAML_METADATA_URL" exception on bottom of this post is thrown.

It seems as well that get_idp_data() isn't present anywhere in current code base.

Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/werkzeug/middleware/proxy_fix.py", line 232, in __call__
    return self.app(environ, start_response)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/web/powerdns-admin/powerdnsadmin/routes/index.py", line 524, in saml_login
    auth = utils.init_saml_auth(req)
  File "/opt/web/powerdns-admin/powerdnsadmin/lib/utils.py", line 211, in init_saml_auth
    metadata = get_idp_data()
NameError: name 'get_idp_data' is not defined

**Comment by ngoduykhanh** [comment]
The function was removed during code refactoring. I've created #603 to re-add it. Can you help to try? I haven't had a chance to test it yet.
