### ISSUE TITLE
[ERROR] werkzeug.routing.BuildError index.login

### ISSUE THREAD

**Issue by Ramalama2** [ngoduykhanh/PowerDNS-Admin#608]
Since the update to Latest (comment 751), i get always this error. same on Centos 7 (python 3.6) or Debian 10 (python 3.7)

Any ideas?

```
[2019-12-16 13:57:40,358] [_internal.py:122] INFO - 127.0.0.1 - - [16/Dec/2019 13:57:40] "GET /login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/werkzeug/middleware/proxy_fix.py", line 232, in __call__
    return self.app(environ, start_response)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/web/powerdns-admin/powerdnsadmin/routes/index.py", line 256, in login
    return render_template('login.html', saml_enabled=SAML_ENABLED)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/opt/web/powerdns-admin/powerdnsadmin/templates/login.html", line 26, in top-level template code
    <a href="{{ url_for('index') }}">DNS-Administration</a>
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'index.login' instead?
```

**Comment by ngoduykhanh** [comment]
Hi, Are you sure you're using the lastest one? The error shows different content for login.html compare to latest master code.

**Comment by Ramalama2** [comment]
ive got it fixed :-( ^^

we had here "ndex" instead of "ndex.index"

<div class="login-logo">
    <a href="{{ url_for('index.index') }}">DNS-Administration</a>
  </div>

We are changing the logo, and that was the problem ^^

Thx All, can be closed :-)
