### ISSUE TITLE
One successful launch, but now ./run.py fails, and Ngnix method fails

### ISSUE THREAD

**Issue by joshbgosh10592** [ngoduykhanh/PowerDNS-Admin#656]
So, I was able to get PowerDNS-Admin installed by using multiple guides, and I was even able to get the WEBUI to load!
However, I started the steps for Ngnix config, and now I can't even get ./run.py to launch.
I'm using Ubuntu 18.04.

/opt/web/powerdns-admin/powerdnsadmin/run.py, when launched:
```
Traceback (most recent call last):
  File "./run.py", line 2, in <module>
    from powerdnsadmin import create_app
  File "/opt/web/powerdns-admin/powerdnsadmin/__init__.py", line 3, in <module>
    from flask import Flask
ImportError: cannot import name 'Flask'
```
And systemctl status powerdns-admin.service:
```
`● powerdns-admin.service - PowerDNS-Admin
   Loaded: loaded (/etc/systemd/system/powerdns-admin.service; enabled; vendor preset: enabled
   Active: failed (Result: exit-code) since Wed 2020-02-05 04:54:15 UTC; 14min ago
 Main PID: 11838 (code=exited, status=3)

Feb 05 04:54:15 powerdns gunicorn[11838]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/
Feb 05 04:54:15 powerdns gunicorn[11838]:     return util.import_app(self.app_uri)
Feb 05 04:54:15 powerdns gunicorn[11838]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/
Feb 05 04:54:15 powerdns gunicorn[11838]:     __import__(module)
Feb 05 04:54:15 powerdns gunicorn[11838]: ModuleNotFoundError: No module named 'app'
Feb 05 04:54:15 powerdns gunicorn[11838]: [2020-02-05 04:54:15 +0000] [11858] [INFO] Worker ex
Feb 05 04:54:15 powerdns gunicorn[11838]: [2020-02-05 04:54:15 +0000] [11838] [INFO] Shutting 
Feb 05 04:54:15 powerdns gunicorn[11838]: [2020-02-05 04:54:15 +0000] [11838] [INFO] Reason: W
Feb 05 04:54:15 powerdns systemd[1]: powerdns-admin.service: Main process exited, code=exited,
Feb 05 04:54:15 powerdns systemd[1]: powerdns-admin.service: Failed with result 'exit-code'.`
```

powerdns-admin.socket is running healthy though!

**Comment by joshbgosh10592** [comment]
Rebooted, and that solved it for some reason....
