### ISSUE TITLE
[bug] Migration script error

### ISSUE THREAD

**Issue by TomSebty** [ngoduykhanh/PowerDNS-Admin#737]
```
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: ALTER TABLE domain_template_record ADD COLUMN comment TEXT]
```

I am using MariaDB 10.4 with Galera. This error happens also with regular Master-Slave replication.
It's a known issue with Galera which doesn't like ALTERs, but every time I start the container I get this error. If anyone can help that would be great!
Thanks

**Comment by ngoduykhanh** [comment]
I think your current DB schema isn't up-to-date. That's was the reason why you keep getting that message every time you start the container.

I think you better to fix the DB server-side problem so you can complete the migration.
```
Lost connection to MySQL server during query
```

**Comment by hasankoroglu** [comment]
I have the same error. With fresh install.

**Comment by hasankoroglu** [comment]
I changed the value of the SQLA_DB_HOST as localhost in the default_config.py file. It was set as 127.0.01 . But now when i run the flask db upgrade it stucks in line below.

`INFO  [alembic.runtime.migration] Running upgrade 0fb6d23a4863 -> 856bb94b7040, Add comment column in domain template record table`

I think it's mysql issue. My server has crashed and not responding.

**Comment by RoeiGanor** [comment]
I'm having this issue too, I'm creating an empty DB for the application to use. When the app is initializing the DB, for some odd reason, it also run `ALTER` command that mess up with the replication. Is there a legitimate way to workaround that? My solution was to backup a standalone deployment and restore it into a replicated cluster.

**Comment by hasankoroglu** [comment]
After hours i get these errors

`INFO  [alembic.runtime.migration] Running upgrade 654298797277 -> 0fb6d23a4863, Remove user avatar
INFO  [alembic.runtime.migration] Running upgrade 0fb6d23a4863 -> 856bb94b7040, Add comment column in domain template record table
Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 88, in <module>
    run_migrations_online()
  File "migrations/env.py", line 81, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/alembic/runtime/migration.py", line 527, in run_migrations
    head_maintainer.update_to_step(step)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/alembic/runtime/migration.py", line 761, in update_to_step
    self._update_version(from_, to_)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/alembic/runtime/migration.py", line 698, in _update_version
    ret = self.context.impl._exec(
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/alembic/ddl/impl.py", line 140, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: UPDATE alembic_version SET version_num='856bb94b7040' WHERE alembic_version.version_num = '0fb6d23a4863']
(Background on this error at: http://sqlalche.me/e/e3q8)
`

**Comment by hasankoroglu** [comment]
Finally i figure out the problem. The problem is on the https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Prepare-MySQL-or-MariaDB-Database-for-PowerDNS-Admin page it says create new db . But powerdnsadmin db upgrade have to be on powerdns db. Bu when i run the db upgrade comman it gives some error as below:

> INFO  [alembic.runtime.migration] Running upgrade 0fb6d23a4863 -> 856bb94b7040, Add comment column in domain template record table
Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator

**Comment by hasankoroglu** [comment]
Problem solved.

Changing db timeout values fixed the problem.

>use mysql;
Set @@local.net_read_timeout = 6000;
SET @@global.net_read_timeout=6000;
