### ISSUE TITLE
access denied mysql non root user

### ISSUE THREAD

**Issue by mhf-ir** [ngoduykhanh/PowerDNS-Admin#821]
Here my docker compose file:
```yml
version: "3"

services:
  app:
    image: ngoduykhanh/powerdns-admin:latest
    container_name: powerdns_admin
    ports:
      - "9865:80"
    depends_on:
      - mariadb
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql://${MYSQL_PDNSA_USER}:${MYSQL_PDNSA_PASS}@mariadb/${MYSQL_PDNSA_DB}"
      GUNICORN_TIMEOUT: "60"
      GUNICORN_WORKERS: "2"
      GUNICORN_LOGLEVEL: DEBUG
      OFFLINE_MODE: "True"

  mariadb:
    image: mariadb:10
    tmpfs: /data-storage
    volumes:
      - ./data-storage:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PDNS_USER=${MYSQL_PDNS_USER}
      - MYSQL_PDNS_PASS=${MYSQL_PDNS_PASS}
      - MYSQL_PDNS_DB=${MYSQL_PDNS_DB}
      - MYSQL_PDNSA_USER=${MYSQL_PDNSA_USER}
      - MYSQL_PDNSA_PASS=${MYSQL_PDNSA_PASS}
      - MYSQL_PDNSA_DB=${MYSQL_PDNSA_DB}
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  adminer:
    image: adminer
    depends_on:
      - mariadb
    ports:
      - 9864:8080
```
Init mariadb:
```bash
#!/bin/bash

cat << EOF > /tmp/init.sql

GRANT ALL PRIVILEGES ON \`${MYSQL_PDNSA_DB}.*\` TO '${MYSQL_PDNSA_USER}'@'%' IDENTIFIED BY '${MYSQL_PDNSA_PASS}';
GRANT ALL PRIVILEGES ON \`${MYSQL_PDNS_DB}.*\` TO '${MYSQL_PDNS_USER}'@'%' IDENTIFIED BY '${MYSQL_PDNS_PASS}';

FLUSH PRIVILEGES;

EOF

echo "================="
cat /tmp/init.sql
echo "================="

mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS \`${MYSQL_PDNS_DB}\`;"
mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS \`${MYSQL_PDNSA_DB}\`;"
mysql -u root -p$MYSQL_ROOT_PASSWORD ${MYSQL_PDNS_DB} < /tmp/init.sql
```

```
Traceback (most recent call last):
  File "/usr/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/usr/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/lib/python3.8/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 88, in <module>
    run_migrations_online()
  File "migrations/env.py", line 72, in run_migrations_online
    connection = engine.connect()
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2209, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 103, in __init__
    else engine.raw_connection()
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2306, in raw_connection
    return self._wrap_pool_connect(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2279, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1547, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 482, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python3.8/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1044, "Access denied for user 'pdnsa-user'@'%' to database 'pdnsa-db'")
(Background on this error at: http://sqlalche.me/e/e3q8)
```

Adminer success login with same credential but powerdns admin could not.

After changine to root user everithing is work well

**Comment by ngoduykhanh** [comment]
The error is straightforward. It was problem with the mysql user permission. PDA itself works fine with the DB connection since you tried with `root` account and it worked. I think you can double-check the `pdnsa-user` user privileges on MySQL server and try some simple query on `pdnsa-db` to confirm.
