### ISSUE TITLE
SAML login not working after upgrade

### ISSUE THREAD

**Issue by Atisom** [ngoduykhanh/PowerDNS-Admin#839]
After I upgraded to ngoduykhanh/powerdns-admin:0.2.3 docker image, the SAML didn't work anymore

<details>
  <summary>Output log</summary>

```
INFO  [alembic.runtime.migration] Context impl SQLiteImpl. 
INFO  [alembic.runtime.migration] Will assume non-transactional DDL. 
[2020-11-23 20:17:20 +0000] [1] [DEBUG] Current configuration: 
  config: None 
  bind: ['0.0.0.0'] 
  backlog: 2048 
  workers: 2 
  worker_class: sync 
  threads: 1 
  worker_connections: 1000 
  max_requests: 0 
  max_requests_jitter: 0 
  timeout: 60 
  graceful_timeout: 30 
  keepalive: 2 
  limit_request_line: 4094 
  limit_request_fields: 100 
  limit_request_field_size: 8190 
  reload: False 
  reload_engine: auto 
  reload_extra_files: [] 
  spew: False 
  check_config: False 
  preload_app: False 
  sendfile: None 
  reuse_port: False 
  chdir: /app 
  daemon: False 
  raw_env: [] 
  pidfile: None 
  worker_tmp_dir: None 
  user: 100 
  group: 101 
  umask: 0 
  initgroups: False 
  tmp_upload_dir: None 
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'} 
  forwarded_allow_ips: ['127.0.0.1'] 
  accesslog: None 
  disable_redirect_access_to_syslog: False 
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" 
  errorlog: - 
  loglevel: DEBUG 
  capture_output: False 
  logger_class: gunicorn.glogging.Logger 
  logconfig: None 
  logconfig_dict: {} 
  syslog_addr: udp://localhost:514 
  syslog: False 
  syslog_prefix: None 
  syslog_facility: user 
  enable_stdio_inheritance: False 
  statsd_host: None 
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None 
  default_proc_name: powerdnsadmin:create_app() 
  pythonpath: None 
  paste: None 
  on_starting: <function OnStarting.on_starting at 0x7f53a5103c10> 
  on_reload: <function OnReload.on_reload at 0x7f53a5103d30> 
  when_ready: <function WhenReady.when_ready at 0x7f53a5103e50> 
  pre_fork: <function Prefork.pre_fork at 0x7f53a5103f70> 
  post_fork: <function Postfork.post_fork at 0x7f53a51190d0> 
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f53a51191f0> 
  worker_int: <function WorkerInt.worker_int at 0x7f53a5119310> 
  worker_abort: <function WorkerAbort.worker_abort at 0x7f53a5119430> 
  pre_exec: <function PreExec.pre_exec at 0x7f53a5119550> 
  pre_request: <function PreRequest.pre_request at 0x7f53a5119670> 
  post_request: <function PostRequest.post_request at 0x7f53a5119700> 
  child_exit: <function ChildExit.child_exit at 0x7f53a5119820> 
  worker_exit: <function WorkerExit.worker_exit at 0x7f53a5119940> 
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f53a5119a60> 
  on_exit: <function OnExit.on_exit at 0x7f53a5119b80> 
  proxy_protocol: False 
  proxy_allow_ips: ['127.0.0.1'] 
  keyfile: None 
  certfile: None 
  ssl_version: 2 
  cert_reqs: 0 
  ca_certs: None 
  suppress_ragged_eofs: True 
  do_handshake_on_connect: False 
  ciphers: None 
  raw_paste_global_conf: [] 
  strip_header_spaces: False 
[2020-11-23 20:17:20 +0000] [1] [INFO] Starting gunicorn 20.0.4 
[2020-11-23 20:17:20 +0000] [1] [DEBUG] Arbiter booted 
[2020-11-23 20:17:20 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1) 
[2020-11-23 20:17:20 +0000] [1] [INFO] Using worker: sync 
[2020-11-23 20:17:20 +0000] [9] [INFO] Booting worker with pid: 9 
[2020-11-23 20:17:20 +0000] [10] [INFO] Booting worker with pid: 10 
[2020-11-23 20:17:20 +0000] [1] [DEBUG] 2 workers 
[2020-11-23 20:17:25 +0000] [9] [DEBUG] GET / 
[2020-11-23 20:17:25 +0000] [9] [DEBUG] GET /login 
[2020-11-23 20:17:25 +0000] [9] [DEBUG] GET /static/generated/login.css 
[2020-11-23 20:17:25 +0000] [10] [DEBUG] GET /static/generated/login.js 
[2020-11-23 20:17:25 +0000] [9] [DEBUG] GET /static/generated/validation.js 
[2020-11-23 20:17:26 +0000] [10] [DEBUG] GET /static/generated/blue@2x.png 
[2020-11-23 20:17:26 +0000] [9] [DEBUG] GET /static/img/favicon.png 
[2020-11-23 20:17:27 +0000] [9] [DEBUG] GET /saml/login 
[2020-11-23 20:17:27 +0000] [9] [ERROR] Exception on /saml/login [GET] 
Traceback (most recent call last): 
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app 
    response = self.full_dispatch_request() 
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request 
    rv = self.handle_user_exception(e) 
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception 
    reraise(exc_type, exc_value, tb) 
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise 
    raise value 
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request 
    rv = self.dispatch_request() 
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request 
    return self.view_functions[rule.endpoint](**req.view_args) 
  File "/app/powerdnsadmin/routes/index.py", line 827, in saml_login 
    auth = saml.init_saml_auth(req) 
  File "/app/powerdnsadmin/services/saml.py", line 125, in init_saml_auth 
    create_self_signed_cert() 
  File "/app/powerdnsadmin/lib/certutil.py", line 45, in create_self_signed_cert 
    open(CERT_FILE, "bw").write( 
PermissionError: [Errno 13] Permission denied: '/app/saml_cert.crt' 
[2020-11-23 20:17:27,228] [app.py:1891] ERROR - Exception on /saml/login [GET] 
Traceback (most recent call last): 
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app 
    response = self.full_dispatch_request() 
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request 
    rv = self.handle_user_exception(e) 
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception 
    reraise(exc_type, exc_value, tb) 
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise 
    raise value 
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request 
    rv = self.dispatch_request() 
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request 
    return self.view_functions[rule.endpoint](**req.view_args) 
  File "/app/powerdnsadmin/routes/index.py", line 827, in saml_login 
    auth = saml.init_saml_auth(req) 
  File "/app/powerdnsadmin/services/saml.py", line 125, in init_saml_auth 
    create_self_signed_cert() 
  File "/app/powerdnsadmin/lib/certutil.py", line 45, in create_self_signed_cert 
    open(CERT_FILE, "bw").write( 
PermissionError: [Errno 13] Permission denied: '/app/saml_cert.crt' 
[2020-11-23 20:17:27 +0000] [9] [DEBUG] GET /static/generated/main.css 
[2020-11-23 20:17:27 +0000] [10] [DEBUG] GET /static/generated/main.js 
[2020-11-23 20:17:27 +0000] [10] [DEBUG] GET /static/fonts/fontawesome-webfont.woff2 
```
  
</details>

I think the permission of the /app directory is not the best:
```
/app $ id
uid=100(pda) gid=101(pda) groups=101(pda)
/app $ ls -lad /app
drwxr-xr-x    1 root     pda           4096 Nov 23 20:20 /app
```
so I cannot copy my certificate

**Comment by Atisom** [comment]
btw I don't understand why want to created a new cert, because I set the envrionments:

```
      - SAML_CERT_KEY=/cert/tls.key
      - SAML_CERT_FILE=/cert/tls.crt
```



The app generated a new cert for the SAML, but I set the path to the
