### ISSUE TITLE
Cannot delete domain.

### ISSUE THREAD

**Issue by falkowich** [ngoduykhanh/PowerDNS-Admin#915]
Updated yesterday to:
https://hub.docker.com/layers/ngoduykhanh/powerdns-admin/latest/images/sha256-2d48412f49c9b1b76ed9430736a787ca6267ec8c63c3504c0bcc71b25a784a7a

When we try to delete domains this happens.

```
powerdns_admin | [2021-03-30 14:12:31,302] [domain.py:142] DEBUG - Traceback (most recent call last):
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
powerdns_admin |     self.dialect.do_execute(
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
powerdns_admin |     cursor.execute(statement, parameters)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
powerdns_admin |     res = self._query(query)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
powerdns_admin |     db.query(q)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
powerdns_admin |     _mysql.connection.query(self, query)
powerdns_admin | MySQLdb._exceptions.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`pda`.`history`, CONSTRAINT `fk_domain_id` FOREIGN KEY (`domain_id`) REFERENCES `domain` (`id`))')
powerdns_admin | 
powerdns_admin | The above exception was the direct cause of the following exception:
powerdns_admin | 
powerdns_admin | Traceback (most recent call last):
powerdns_admin |   File "/app/powerdnsadmin/models/domain.py", line 138, in update
powerdns_admin |     self.delete_domain_from_pdnsadmin(domain_name, do_commit=False)
powerdns_admin |   File "/app/powerdnsadmin/models/domain.py", line 523, in delete_domain_from_pdnsadmin
powerdns_admin |     Domain.query.filter(Domain.name == domain_name).delete()
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3899, in delete
powerdns_admin |     delete_op.exec_()
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1697, in exec_
powerdns_admin |     self._do_exec()
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1928, in _do_exec
powerdns_admin |     self._execute_stmt(delete_stmt)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1702, in _execute_stmt
powerdns_admin |     self.result = self.query._execute_crud(stmt, self.mapper)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3541, in _execute_crud
powerdns_admin |     return conn.execute(stmt, self._params)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
powerdns_admin |     return meth(self, multiparams, params)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
powerdns_admin |     return connection._execute_clauseelement(self, multiparams, params)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
powerdns_admin |     ret = self._execute_context(
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
powerdns_admin |     self._handle_dbapi_exception(
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
powerdns_admin |     util.raise_(
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
powerdns_admin |     raise exception
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
powerdns_admin |     self.dialect.do_execute(
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
powerdns_admin |     cursor.execute(statement, parameters)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
powerdns_admin |     res = self._query(query)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
powerdns_admin |     db.query(q)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
powerdns_admin |     _mysql.connection.query(self, query)
powerdns_admin | sqlalchemy.exc.IntegrityError: (MySQLdb._exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`pda`.`history`, CONSTRAINT `fk_domain_id` FOREIGN KEY (`domain_id`) REFERENCES `domain` (`id`))')
powerdns_admin | [SQL: DELETE FROM domain WHERE domain.name = %s]
powerdns_admin | [parameters: ('example.com',)]
powerdns_admin | (Background on this error at: http://sqlalche.me/e/13/gkpj)
powerdns_admin | 
powerdns_admin | [2021-03-30 14:12:31 +0000] [10] [INFO] Update domain finished
powerdns_admin | [2021-03-30 14:12:31,332] [domain.py:161] INFO - Update domain finished
powerdns_admin | [2021-03-30 14:12:31 +0000] [11] [DEBUG] GET /dashboard/domains-custom/reverse
powerdns_admin | [2021-03-30 14:12:31 +0000] [10] [DEBUG] GET /dashboard/domains-custom/ip6arpa
powerdns_admin | [2021-03-30 14:12:31 +0000] [11] [DEBUG] GET /dashboard/domains-custom/inaddrarpa

```
Any ideas out there?

--  
Regards Falk

**Comment by falkowich** [comment]
The domain is deleted from "powerdns" db throu the API.
But it is still in the "pda" db:

```
MariaDB [pda]> select * from domain;

| 13 | example.com                   | []     | Native | 2021033001 |               0 |          0 |      0 |       NULL |
```

MariaDB [pda]> select * from  history where id=164
```
| 164 | Applying template Default to example.com successfully.                     | {"domain": "example.com", "template": "Default", "add_rrests": [{"name": "example.com.", "type": "NS", "ttl": 86400, "records": [{"content": "ns2.example.se.", "disabled": false}, {"content": "ns3.example.se.", "disabled": false}], "comments": [{"content": "", "account": ""}, {"content": "", "account": ""}], "changetype": "REPLACE"}, {"name": "example.com.", "type": "SOA", "ttl": 3600, "records": [{"content": "ns2.example.se. hostmaster.example.se. 2020102003 86400 7200 3600000 172800", "disabled": false}], "comments": [{"content": "", "account": ""}], "changetype": "REPLACE"}], "del_rrests": []}                                                                                                                                                                                                                                                                                                                                                                                                                                           |user_name_here | 2021-03-30 14:11:08 |        13 |
```

**Comment by falkowich** [comment]
I can confirm that this is happening with "every" delete.

Delete goes bonkers.

```
powerdns_admin | [2021-03-30 14:46:07 +0000] [11] [DEBUG] GET /domain/setting/example.com/manage
powerdns_admin | [2021-03-30 14:46:11 +0000] [10] [DEBUG] POST /domain/setting/example.com/delete
powerdns_admin | [2021-03-30 14:46:11 +0000] [10] [INFO] Deleted domain successfully from PowerDNS: example.com
powerdns_admin | [2021-03-30 14:46:11,356] [domain.py:504] INFO - Deleted domain successfully from PowerDNS: example.com
powerdns_admin | [2021-03-30 14:46:11 +0000] [10] [ERROR] Cannot delete domain example.com
powerdns_admin | [2021-03-30 14:46:11,366] [domain.py:485] ERROR - Cannot delete domain example.com
powerdns_admin | [2021-03-30 14:46:11 +0000] [10] [ERROR] (MySQLdb._exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`pda`.`history`, CONSTRAINT `fk_domain_id` FOREIGN KEY (`domain_id`) REFERENCES `domain` (`id`))')
````
Then history gets cleared, and the delete gets done..

**Comment by falkowich** [comment]
Are there some alembic db migration that I missed with the latest update.
I thougt that the docker upstart script took care of that?

--  
Regards Falk

**Comment by RoeiGanor** [comment]
There was an update few days ago by @jodygilbert thats look related:
https://github.com/ngoduykhanh/PowerDNS-Admin/commit/98db953820a40356df2d884774f01de3fa828533

I think that deleting domain is a use case that was not tested on this PR.

**Comment by jodygilbert** [comment]
that's really odd, deletes are working fine for me, but I'm not using mariadb so it appears sqllite is behaving differently.  I'll add logic to the domain delete to remove the domain id from the history table, which should fix this for mariadb.

**Comment by sellerie98** [comment]
Can confirm that deleting domains with a mysql/mariadb backend is now working just fine.

**Comment by falkowich** [comment]
I can confirm this fix.
Updated today and deletion worked.

Thanks for the great support!

--
Regards Falk
