### ISSUE TITLE
500 Oops! Something went wrong (record comments)

### ISSUE THREAD

**Issue by Revertron** [ngoduykhanh/PowerDNS-Admin#924]
Sometimes, for some of domains, if I add some comment, I can't open that domain no more.
Comments are simple, one word, like Netherlands or something similar.
Installed by docker, latest version for now.

```
[2021-04-18 10:18:00,155] [app.py:1890] ERROR - Exception on /domain/alfis.name [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.8/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/app/powerdnsadmin/decorators.py", line 60, in decorated_function
    return f(*args, **kwargs)
  File "/app/powerdnsadmin/routes/domain.py", line 108, in domain
    comment=r['comments'][index]['content']
IndexError: list index out of range

```

**Comment by Revertron** [comment]
Oops! I didn't have the latest version after all.
After an upgrade of docker container it started to work.
