### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'account_user_ids' is undefined

### ISSUE THREAD

**Issue by qwertiko** [ngoduykhanh/PowerDNS-Admin#937]
When trying to create a new Account a `jinja2.exceptions.UndefinedError:` Error gets thrown:

```
(flask) root@hostname:/srv/www/PowerDNS-Admin# ./run.py
 * Serving Flask app "powerdnsadmin" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
[2021-06-01 11:44:35,486] [_internal.py:225] INFO -  * Running on http://000.000.000.000:9191/ (Press CTRL+C to quit)
[2021-06-01 11:44:35,487] [_internal.py:225] INFO -  * Restarting with stat
[2021-06-01 11:44:35,989] [_internal.py:225] WARNING -  * Debugger is active!
[2021-06-01 11:44:35,989] [_internal.py:225] INFO -  * Debugger PIN: 000-000-000
[2021-06-01 11:44:42,755] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:42] "GET / HTTP/1.1" 302 -
[2021-06-01 11:44:42,859] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:42] "GET /login HTTP/1.1" 200 -
[2021-06-01 11:44:43,072] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:43] "GET /static/generated/login.css?2a708f5e HTTP/1.1" 200 -
[2021-06-01 11:44:43,076] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:43] "GET /static/generated/login.js?7563eb97 HTTP/1.1" 200 -
[2021-06-01 11:44:43,081] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:43] "GET /static/generated/validation.js?99acceba HTTP/1.1" 200 -
[2021-06-01 11:44:43,322] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:43] "GET /static/img/favicon.png HTTP/1.1" 200 -
[2021-06-01 11:44:53,312] [user.py:209] INFO - User "powerdnsadmin" logged in successfully. Authentication request from 000.000.000.000
[2021-06-01 11:44:53,312] [index.py:502] INFO - User powerdnsadmin authenticated successfully via LOCAL from 000.000.000.000
[2021-06-01 11:44:53,316] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:53] "POST /login HTTP/1.1" 302 -
[2021-06-01 11:44:53,426] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:53] "GET / HTTP/1.1" 302 -
[2021-06-01 11:44:53,508] [dashboard.py:148] INFO - Updating domains in foreground...
[2021-06-01 11:44:53,522] [domain.py:119] INFO - Found 0000 domains in PowerDNS-Admin
[2021-06-01 11:44:54,020] [domain.py:130] INFO - Found 0000 zones in PowerDNS server
[2021-06-01 11:44:56,479] [domain.py:161] INFO - Update domain finished
[2021-06-01 11:44:56,595] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:56] "GET /dashboard/ HTTP/1.1" 200 -
[2021-06-01 11:44:56,818] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:56] "GET /static/generated/main.css?1077ba1d HTTP/1.1" 200 -
[2021-06-01 11:44:56,821] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:56] "GET /static/generated/main.js?0dbcfa21 HTTP/1.1" 200 -
[2021-06-01 11:44:57,049] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:57] "GET /static/node_modules/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 -
[2021-06-01 11:44:57,283] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:57] "GET /static/node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 -
[2021-06-01 11:44:57,294] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:57] "GET /dashboard/domains-custom/ip6arpa?draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=false&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1622540697114 HTTP/1.1" 200 -
[2021-06-01 11:44:57,297] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:57] "GET /dashboard/domains-custom/reverse?draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=false&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1622540697113 HTTP/1.1" 200 -
[2021-06-01 11:44:57,298] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:57] "GET /dashboard/domains-custom/inaddrarpa?draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=false&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1622540697115 HTTP/1.1" 200 -
[2021-06-01 11:44:57,401] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:44:57] "GET /static/img/favicon.png HTTP/1.1" 304 -
[2021-06-01 11:45:00,307] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:45:00] "GET /admin/manage-account HTTP/1.1" 200 -
[2021-06-01 11:45:00,535] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:45:00] "GET /static/generated/main.js?0dbcfa21 HTTP/1.1" 304 -
[2021-06-01 11:45:00,819] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:45:00] "GET /static/img/favicon.png HTTP/1.1" 304 -
[2021-06-01 11:45:01,977] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:45:01] "GET /admin/account/edit HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/srv/www/PowerDNS-Admin/flask/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/srv/www/PowerDNS-Admin/flask/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/srv/www/PowerDNS-Admin/flask/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/srv/www/PowerDNS-Admin/flask/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/www/PowerDNS-Admin/flask/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/srv/www/PowerDNS-Admin/flask/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/www/PowerDNS-Admin/flask/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/www/PowerDNS-Admin/flask/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/www/PowerDNS-Admin/flask/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/srv/www/PowerDNS-Admin/flask/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/www/PowerDNS-Admin/flask/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/www/PowerDNS-Admin/flask/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/srv/www/PowerDNS-Admin/powerdnsadmin/decorators.py", line 32, in decorated_function
    return f(*args, **kwargs)
  File "/srv/www/PowerDNS-Admin/powerdnsadmin/routes/admin.py", line 442, in edit_account
    return render_template('admin_edit_account.html',
  File "/srv/www/PowerDNS-Admin/flask/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/srv/www/PowerDNS-Admin/flask/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/srv/www/PowerDNS-Admin/flask/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/srv/www/PowerDNS-Admin/flask/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/srv/www/PowerDNS-Admin/powerdnsadmin/templates/admin_edit_account.html", line 2, in top-level template code
    {% set active_page = "admin_accounts" %}
  File "/srv/www/PowerDNS-Admin/powerdnsadmin/templates/base.html", line 183, in top-level template code
    {% block content %}
  File "/srv/www/PowerDNS-Admin/powerdnsadmin/templates/admin_edit_account.html", line 87, in block 'content'
    <option {% if user.id in account_user_ids %}selected{% endif %}
jinja2.exceptions.UndefinedError: 'account_user_ids' is undefined
[2021-06-01 11:45:02,214] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:45:02] "GET /admin/account/edit?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[2021-06-01 11:45:02,224] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:45:02] "GET /admin/account/edit?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
[2021-06-01 11:45:02,314] [_internal.py:225] INFO - 000.000.000.000 - - [01/Jun/2021 11:45:02] "GET /admin/account/edit?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

We are using a fresh installation and everything else seems to work fine.

**Comment by melck** [comment]
Same bug for us. We temporary fix it by changing this template file :
```diff
diff --git a/powerdnsadmin/templates/admin_edit_account.html b/powerdnsadmin/templates/admin_edit_account.html
index 10344a8..41f2d43 100644
--- a/powerdnsadmin/templates/admin_edit_account.html
+++ b/powerdnsadmin/templates/admin_edit_account.html
@@ -84,7 +84,7 @@
                             <select multiple="multiple" class="form-control" id="account_multi_user"
                                 name="account_multi_user">
                                 {% for user in users %}
-                                <option {% if user.id in account_user_ids %}selected{% endif %}
+                                <option {% if user.id in account_user_ids|default([]) %}selected{% endif %}
                                     value="{{ user.username }}">{{ user.username }}</option>
                                 {% endfor %}
                             </select>
@@ -162,4 +162,4 @@
         }
     });
 </script>
-{% endblock %}
\ No newline at end of file
+{% endblock %}
```

**Comment by qwertiko** [comment]
Hey @melck thanks for the workaround, I just tested that and it does indeed work! :smile:

**Comment by sfoutrel** [comment]
I'm a beginner in Python so excuse me if this is not relevant.
I found in the setup.py of flask 1.1.2 (which is in the requirement.txt) https://github.com/pallets/flask/blob/1.1.2/setup.py
this line that seems to say that python after 3.4.X is not supported :
` python_requires=">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*",`

**Comment by psingh0912** [comment]
Hi @melck , I tried your workaround but I still have the same error.

```
Jun 23 14:50:13 powerdns-master gunicorn[5780]:     <option {% if user.id in account_user_ids|default([]) %}selected{% endif %}
Jun 23 14:50:13 powerdns-master gunicorn[5780]: jinja2.exceptions.UndefinedError: 'account_user_ids' is undefined
```

Can you post a full copy of your working template?

Thanks in advance!

**Comment by steschuser** [comment]
I just made a pull request for this, setting account_user_ids=[] in routes/admin
@psingh0912 Does this work better for you?

**Comment by psingh0912** [comment]
> I just made a pull request for this, setting account_user_ids=[] in routes/admin
> @psingh0912 Does this work better for you?

Hi @steschuser, This worked beautifully! Thank you so much.

**Comment by dmgeurts** [comment]
I'm still experiencing this issue, even after a git pull.

```
Aug 12 13:43:26 web07 gunicorn[552213]: [2021-08-12 13:43:26,358] [app.py:1891] ERROR - Exception on /admin/account/edit [GET]
Aug 12 13:43:26 web07 gunicorn[552213]: Traceback (most recent call last):
Aug 12 13:43:26 web07 gunicorn[552213]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
Aug 12 13:43:26 web07 gunicorn[552213]:     response = self.full_dispatch_request()
Aug 12 13:43:26 web07 gunicorn[552213]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
Aug 12 13:43:26 web07 gunicorn[552213]:     rv = self.handle_user_exception(e)
Aug 12 13:43:26 web07 gunicorn[552213]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
Aug 12 13:43:26 web07 gunicorn[552213]:     reraise(exc_type, exc_value, tb)
Aug 12 13:43:26 web07 gunicorn[552213]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
Aug 12 13:43:26 web07 gunicorn[552213]:     raise value
Aug 12 13:43:26 web07 gunicorn[552213]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
Aug 12 13:43:26 web07 gunicorn[552213]:     rv = self.dispatch_request()
Aug 12 13:43:26 web07 gunicorn[552213]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
Aug 12 13:43:26 web07 gunicorn[552213]:     return self.view_functions[rule.endpoint](**req.view_args)
Aug 12 13:43:26 web07 gunicorn[552213]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
Aug 12 13:43:26 web07 gunicorn[552213]:     return func(*args, **kwargs)
Aug 12 13:43:26 web07 gunicorn[552213]:   File "/var/www/html/pdns/powerdnsadmin/decorators.py", line 32, in decorated_function
Aug 12 13:43:26 web07 gunicorn[552213]:     return f(*args, **kwargs)
Aug 12 13:43:26 web07 gunicorn[552213]:   File "/var/www/html/pdns/powerdnsadmin/routes/admin.py", line 442, in edit_account
Aug 12 13:43:26 web07 gunicorn[552213]:     if account_name is None:
Aug 12 13:43:26 web07 gunicorn[552213]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
Aug 12 13:43:26 web07 gunicorn[552213]:     return _render(
Aug 12 13:43:26 web07 gunicorn[552213]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
Aug 12 13:43:26 web07 gunicorn[552213]:     rv = template.render(context)
Aug 12 13:43:26 web07 gunicorn[552213]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
Aug 12 13:43:26 web07 gunicorn[552213]:     self.environment.handle_exception()
Aug 12 13:43:26 web07 gunicorn[552213]:   File "/var/www/html/pdns/flask/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
Aug 12 13:43:26 web07 gunicorn[552213]:     raise rewrite_traceback_stack(source=source)
Aug 12 13:43:26 web07 gunicorn[552213]:   File "/var/www/html/pdns/powerdnsadmin/templates/admin_edit_account.html", line 2, in top-level template code
Aug 12 13:43:26 web07 gunicorn[552213]:     {% set active_page = "admin_accounts" %}
Aug 12 13:43:26 web07 gunicorn[552213]:   File "/var/www/html/pdns/powerdnsadmin/templates/base.html", line 183, in top-level template code
Aug 12 13:43:26 web07 gunicorn[552213]:     {% block content %}
Aug 12 13:43:26 web07 gunicorn[552213]:   File "/var/www/html/pdns/powerdnsadmin/templates/admin_edit_account.html", line 87, in block 'content'
Aug 12 13:43:26 web07 gunicorn[552213]:     <option {% if user.id in account_user_ids|default([]) %}selected{% endif %}
Aug 12 13:43:26 web07 gunicorn[552213]: jinja2.exceptions.UndefinedError: 'account_user_ids' is undefined
```
