### ISSUE TITLE
BUG | Admin create api key

### ISSUE THREAD

**Issue by melck** [ngoduykhanh/PowerDNS-Admin#938]
When access to route `admin/key/edit`, result is an error HTTP 500.

## To reproduce

- Start from a new install
- Login as admin
- Go to menu > API Keys
- Click on button "Add Key" 

## Traceback 

```
Traceback (most recent call last):
  File "/opt/PowerDNS-Admin/flask/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/PowerDNS-Admin/flask/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/PowerDNS-Admin/flask/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/PowerDNS-Admin/flask/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/PowerDNS-Admin/flask/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/PowerDNS-Admin/flask/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/PowerDNS-Admin/flask/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/opt/PowerDNS-Admin/powerdnsadmin/decorators.py", line 32, in decorated_function
    return f(*args, **kwargs)
  File "/opt/PowerDNS-Admin/powerdnsadmin/routes/admin.py", line 161, in edit_key
    create=create)
  File "/opt/PowerDNS-Admin/flask/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/opt/PowerDNS-Admin/flask/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/opt/PowerDNS-Admin/flask/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/opt/PowerDNS-Admin/flask/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/PowerDNS-Admin/powerdnsadmin/templates/admin_edit_key.html", line 2, in top-level template code
    {% set active_page = "admin_keys" %}
  File "/opt/PowerDNS-Admin/powerdnsadmin/templates/base.html", line 183, in top-level template code
    {% block content %}
  File "/opt/PowerDNS-Admin/powerdnsadmin/templates/admin_edit_key.html", line 62, in block 'content'
    <option {% if domain in key.domains %}selected{% endif %} value="{{ domain.name }}">{{ domain.name }}</option>
jinja2.exceptions.UndefinedError: 'None' has no attribute 'domains'
```

## Workarround

```diff
diff --git a/powerdnsadmin/templates/admin_edit_key.html b/powerdnsadmin/templates/admin_edit_key.html
index f1a33a0..d89cad1 100644
--- a/powerdnsadmin/templates/admin_edit_key.html
+++ b/powerdnsadmin/templates/admin_edit_key.html
@@ -59,7 +59,7 @@
                             <select multiple="multiple" class="form-control" id="key_multi_domain"
                                 name="key_multi_domain">
                                 {% for domain in domains %}
-                                    <option {% if domain in key.domains %}selected{% endif %} value="{{ domain.name }}">{{ domain.name }}</option>
+                                    <option {% if key and domain in key.domains %}selected{% endif %} value="{{ domain.name }}">{{ domain.name }}</option>
                                 {% endfor %}
                             </select>
                         </div>
@@ -165,4 +165,4 @@
     </div>
     <!-- /.modal-dialog -->
 </div>
-{% endblock %}
\ No newline at end of file
+{% endblock %}
```

**Comment by RoeiGanor** [comment]
Hey @melck, can you elaborate on this bug and how to reproduce it?

**Comment by sfoutrel** [comment]
git clone master on Debian Buster.
install as explained in the doc.
log-in as admin, try to create a new api key. End in Error 500.

**Comment by Tchad90** [comment]
Hi,
Thank u for the workaround, i can now access the API key menu but when i create new API key i got this issue :

[2021-06-03 09:51:50,659] [_internal.py:225] INFO - 10.22.254.2 - - [03/Jun/2021 09:51:50] "POST /admin/key/edit HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/opt/web/powerdns-admin/powerdnsadmin/decorators.py", line 32, in decorated_function
    return f(*args, **kwargs)
  File "/opt/web/powerdns-admin/powerdnsadmin/routes/admin.py", line 174, in edit_key
    domains=domain_obj_list)
  File "<string>", line 4, in __init__

  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/opt/web/powerdns-admin/powerdnsadmin/models/api_key.py", line 32, in __init__
    self.key = self.get_hashed_password(rand_key).decode('utf-8')
  File "/opt/web/powerdns-admin/powerdnsadmin/models/api_key.py", line 91, in get_hashed_password
    current_app.config.get('SALT').encode('utf-8'))
  File "/opt/web/powerdns-admin/flask/lib/python3.7/site-packages/bcrypt/__init__.py", line 105, in hashpw
    raise ValueError("Invalid salt")
ValueError: Invalid salt

Can someone help me please ?

Have a nice day

![2021-06-03_09h52_11](https://user-images.githubusercontent.com/85280463/120608398-73da1800-c451-11eb-9dea-ca1870439a7c.png)

**Comment by melck** [comment]
@Tchad90 We have same issue. I looked up in code and salt must be a bcrypt's salt. To generate it, you can do this :
```
source flask/bin/activate
export FLASK_APP=./powerdnsadmin/__init__.py
python -c 'import bcrypt; print(bcrypt.gensalt().decode())'
```
Then add to config file the generated salt.

**Comment by melck** [comment]
@RoeiGanor I have added stepsto reproduce, but its really a obvious bug. I didn't thought it needed more details ;)
