### ISSUE TITLE
Error when add new account

### ISSUE THREAD

**Issue by vhostvn** [ngoduykhanh/PowerDNS-Admin#945]
Hi,

I just try PowerDNS-Admin today and we get this error while trying to add new Account.

**Error:**

`jinja2.exceptions.UndefinedError
jinja2.exceptions.UndefinedError: 'account_user_ids' is undefined

Traceback (most recent call last)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
return self.app(environ, start_response)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    import collections.abc as collections_abc
 
    def reraise(tp, value, tb=None):
        if value.__traceback__ is not tb:
            raise value.with_traceback(tb)
        raise value
 
    implements_to_string = _identity
 
else:
    iterkeys = lambda d: d.iterkeys()
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/opt/web/powerdns-admin/powerdnsadmin/decorators.py", line 32, in decorated_function
return f(*args, **kwargs)
File "/opt/web/powerdns-admin/powerdnsadmin/routes/admin.py", line 444, in edit_account
create=1)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
ctx.app,
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
rv = template.render(context)
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/jinja2/environment.py", line 1304, in render
self.environment.handle_exception()
File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/jinja2/environment.py", line 925, in handle_exception
raise rewrite_traceback_stack(source=source)
File "/opt/web/powerdns-admin/powerdnsadmin/templates/admin_edit_account.html", line 2, in top-level template code
{% set active_page = "admin_accounts" %}
File "/opt/web/powerdns-admin/powerdnsadmin/templates/base.html", line 183, in top-level template code
{% block content %}
File "/opt/web/powerdns-admin/powerdnsadmin/templates/admin_edit_account.html", line 87, in block 'content'
<option {% if user.id in account_user_ids %}selected{% endif %}
jinja2.exceptions.UndefinedError: 'account_user_ids' is undefined
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.`

**My environment:**

`[root@powerdns-admin-centos7 ~]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

[root@powerdns-admin-centos7 ~]# mysql -V
mysql  Ver 15.1 Distrib 10.5.10-MariaDB, for Linux (x86_64) using readline 5.1

[root@powerdns-admin-centos7 ~]# pdns_control version
4.2.3`

May I know how to fix this issue?

Thanks,
<img width="588" alt="20210602-20-02-39" src="https://user-images.githubusercontent.com/16444776/120484803-a0544c80-c3dd-11eb-8abe-0bc2c5bd5f5b.png">

**Comment by dimpapac** [comment]
I had the same problem, this fix https://github.com/ngoduykhanh/PowerDNS-Admin/issues/937#issuecomment-852013805 seems to work.

**Comment by vhostvn** [comment]
Thanks, case #937 worked for me.
