### ISSUE TITLE
MariaDB Galera DB schema create failed

### ISSUE THREAD

**Issue by larslehmann-net** [ngoduykhanh/PowerDNS-Admin#967]
When creating the database schema in my Mariadb 10.5 Galera cluster with InnoDB Engine I get the following error `This table type requires a primary key`. 

```
Attaching to powerdns_powerdns_admin_1
powerdns_admin_1  | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
powerdns_admin_1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
powerdns_admin_1  | INFO  [alembic.runtime.migration] Running upgrade  -> 787bdba9e147, Init DB
powerdns_admin_1  | INFO  [alembic.runtime.migration] Running upgrade 787bdba9e147 -> 59729e468045, Add view column to setting table
powerdns_admin_1  | INFO  [alembic.runtime.migration] Running upgrade 59729e468045 -> 1274ed462010, Change setting.value data type
powerdns_admin_1  | INFO  [alembic.runtime.migration] Running upgrade 1274ed462010 -> 4a666113c7bb, Adding Operator Role
powerdns_admin_1  | INFO  [alembic.runtime.migration] Running upgrade 4a666113c7bb -> 31a4ed468b18, Remove all setting in the DB
powerdns_admin_1  | INFO  [alembic.runtime.migration] Running upgrade 31a4ed468b18 -> 654298797277, Upgrade DB Schema
powerdns_admin_1  | Traceback (most recent call last):
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
powerdns_admin_1  |     self.dialect.do_execute(
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
powerdns_admin_1  |     cursor.execute(statement, parameters)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
powerdns_admin_1  |     res = self._query(query)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
powerdns_admin_1  |     db.query(q)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
powerdns_admin_1  |     _mysql.connection.query(self, query)
powerdns_admin_1  | MySQLdb._exceptions.OperationalError: (1173, 'This table type requires a primary key')
powerdns_admin_1  | 
powerdns_admin_1  | The above exception was the direct cause of the following exception:
powerdns_admin_1  | 
powerdns_admin_1  | Traceback (most recent call last):
powerdns_admin_1  |   File "/usr/bin/flask", line 8, in <module>
powerdns_admin_1  |     sys.exit(main())
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/flask/cli.py", line 967, in main
powerdns_admin_1  |     cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/flask/cli.py", line 586, in main
powerdns_admin_1  |     return super(FlaskGroup, self).main(*args, **kwargs)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
powerdns_admin_1  |     rv = self.invoke(ctx)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
powerdns_admin_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
powerdns_admin_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
powerdns_admin_1  |     return ctx.invoke(self.callback, **ctx.params)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
powerdns_admin_1  |     return callback(*args, **kwargs)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
powerdns_admin_1  |     return f(get_current_context(), *args, **kwargs)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
powerdns_admin_1  |     return __ctx.invoke(f, *args, **kwargs)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
powerdns_admin_1  |     return callback(*args, **kwargs)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/flask_migrate/cli.py", line 134, in upgrade
powerdns_admin_1  |     _upgrade(directory, revision, sql, tag, x_arg)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/flask_migrate/__init__.py", line 96, in wrapped
powerdns_admin_1  |     f(*args, **kwargs)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/flask_migrate/__init__.py", line 271, in upgrade
powerdns_admin_1  |     command.upgrade(config, revision, sql=sql, tag=tag)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/alembic/command.py", line 294, in upgrade
powerdns_admin_1  |     script.run_env()
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/alembic/script/base.py", line 490, in run_env
powerdns_admin_1  |     util.load_python_file(self.dir, "env.py")
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
powerdns_admin_1  |     module = load_module_py(module_id, path)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/alembic/util/compat.py", line 182, in load_module_py
powerdns_admin_1  |     spec.loader.exec_module(module)
powerdns_admin_1  |   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
powerdns_admin_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
powerdns_admin_1  |   File "/app/migrations/env.py", line 88, in <module>
powerdns_admin_1  |     run_migrations_online()
powerdns_admin_1  |   File "/app/migrations/env.py", line 81, in run_migrations_online
powerdns_admin_1  |     context.run_migrations()
powerdns_admin_1  |   File "<string>", line 8, in run_migrations
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
powerdns_admin_1  |     self.get_context().run_migrations(**kw)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/alembic/runtime/migration.py", line 561, in run_migrations
powerdns_admin_1  |     step.migration_fn(**kw)
powerdns_admin_1  |   File "/app/migrations/versions/654298797277_add_apikey_schema.py", line 30, in upgrade
powerdns_admin_1  |     op.create_table('domain_apikey',
powerdns_admin_1  |   File "<string>", line 8, in create_table
powerdns_admin_1  |   File "<string>", line 3, in create_table
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/alembic/operations/ops.py", line 1072, in create_table
powerdns_admin_1  |     return operations.invoke(op)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/alembic/operations/base.py", line 354, in invoke
powerdns_admin_1  |     return fn(self, operation)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/alembic/operations/toimpl.py", line 101, in create_table
powerdns_admin_1  |     operations.impl.create_table(table)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/alembic/ddl/impl.py", line 277, in create_table
powerdns_admin_1  |     self._exec(schema.CreateTable(table))
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/alembic/ddl/impl.py", line 146, in _exec
powerdns_admin_1  |     return conn.execute(construct, multiparams)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
powerdns_admin_1  |     return meth(self, multiparams, params)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
powerdns_admin_1  |     return connection._execute_ddl(self, multiparams, params)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
powerdns_admin_1  |     ret = self._execute_context(
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
powerdns_admin_1  |     self._handle_dbapi_exception(
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
powerdns_admin_1  |     util.raise_(
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
powerdns_admin_1  |     raise exception
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
powerdns_admin_1  |     self.dialect.do_execute(
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
powerdns_admin_1  |     cursor.execute(statement, parameters)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
powerdns_admin_1  |     res = self._query(query)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
powerdns_admin_1  |     db.query(q)
powerdns_admin_1  |   File "/usr/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
powerdns_admin_1  |     _mysql.connection.query(self, query)
powerdns_admin_1  | sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1173, 'This table type requires a primary key')
powerdns_admin_1  | [SQL: 
powerdns_admin_1  | CREATE TABLE domain_apikey (
powerdns_admin_1  |     domain_id INTEGER, 
powerdns_admin_1  |     apikey_id INTEGER, 
powerdns_admin_1  |     FOREIGN KEY(apikey_id) REFERENCES apikey (id), 
powerdns_admin_1  |     FOREIGN KEY(domain_id) REFERENCES domain (id)
powerdns_admin_1  | )
powerdns_admin_1  | 
powerdns_admin_1  | ]
powerdns_admin_1  | (Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by RGanor** [comment]
Hey @larslehmann-net!
Is this issue still relevant? Please let us know.

**Comment by larslehmann-net** [comment]
Hello,
yes it is still relevant.
If I understand the error correctly the InnoDB engine needs a primary key in each table.

**Comment by RGanor** [comment]
It seems like domain_apikey really doesnt have primary key. I dont know how other people didnt encountered this issue but it indeed looks like a problem.
I think that an easy fix will be to upgrade the schema and adding an auto increments primary key.
