### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4: ordinal not in range(128)

### ISSUE THREAD

**Issue by FunRaiser1** [ngoduykhanh/PowerDNS-Admin#992]
Hello,

We are facing an issue with powerdnsadmin when trying to open a domain.

Aug 16 08:15:25 ns1-server gunicorn[877634]: [2021-08-16 08:15:25,122] [app.py:1891] ERROR - Exception on /domain/
****hidden*** [GET]
Aug 16 08:15:25 ns1-server gunicorn[877634]: Traceback (most recent call last):
Aug 16 08:15:25 ns1-server gunicorn[877634]:   File "/var/www/html/pdns/powerdnsadmin/lib/utils.py", line 244, in pretty_domain_name
Aug 16 08:15:25 ns1-server gunicorn[877634]:     return value.encode().decode('idna')
Aug 16 08:15:25 ns1-server gunicorn[877634]:   File "/usr/lib/python3.8/encodings/idna.py", line 214, in decode
Aug 16 08:15:25 ns1-server gunicorn[877634]:     result.append(ToUnicode(label))
Aug 16 08:15:25 ns1-server gunicorn[877634]:   File "/usr/lib/python3.8/encodings/idna.py", line 125, in ToUnicode
Aug 16 08:15:25 ns1-server gunicorn[877634]:     return str(label, "ascii")

The issue occurs with the record "v=spf1 include:spf.protection.outlook.com –all".

+--------+-----------+--------------------------+-------+--------------------------------------------------------------------------+-------+------+-----------+------+----------+
| id     | domain_id | name                     | type  | content                                                                  | ttl   | prio | ordername | auth | disabled |
+--------+-----------+--------------------------+-------+--------------------------------------------------------------------------+-------+------+-----------+------+----------+
| 178332 |      2691 | **hidden**              | SOA   | **hidden***. hostmaster.**hidden***. 2021081201 21600 7200 2419200 86400 | 28800 |    0 | NULL      |    1 |        0 |
| 178333 |      2691 | **hidden**              | NS    | **hidden***                                                            | 28800 |    0 | NULL      |    1 |        0 |
| 178334 |      2691 | **hidden**              | NS    | **hidden***                                                            | 28800 |    0 | NULL      |    1 |        0 |
| 178335 |      2691 | **hidden**              | TXT   | "v=spf1 include:spf.protection.outlook.com –all"                         | 28800 |    0 | NULL      |    1 |        0 |
+--------+-----------+--------------------------+-------+--------------------------------------------------------------------------+-------+------+-----------+------+----------+

If we remove id 178335 from the database, the issue is no longer present and the domain is showing up.

If we recreate the record again in powerdns-admin, the domain is again no longer able to open and shows an 500 error again.

Can you please have a check what is going on?

**Comment by FunRaiser1** [comment]
it seems that the creation of the txt record was made incorrect but i could not identify that there are special characters in the record.
I only saw it using "dig".
           3600    IN      TXT     "v=spf1 include:spf.protection.outlook.com \226\128\147all"
